In [5]:
import pandas as pd

In [11]:
df= pd.read_csv('./pandas_03_DDA2.csv', index_col=0)
df

         종목명    종목코드     현재가      거래량  지역
0       삼성전자    5930   70000  1000000  서울
1     SK하이닉스     660  120000   800000  서울
2      NAVER   35420  380000   500000  성남
3        카카오   35720  135000   600000  성남
4       LG화학   51910  800000   300000  서울
5        현대차    5380  200000   400000  울산
6      POSCO    5490  300000   200000  포항
7       KB금융  105560   45000   700000  서울
8       신한지주   55550   42000   650000  서울
9       셀트리온   68270  230000   550000  인천
10     카카오뱅크  323410   65000   450000  서울
11  삼성바이오로직스  207940  800000   350000  서울
12     삼성SDI    6400  200000   250000  서울
13      LG전자   66570  150000   850000  서울
14      KT&G   33780   85000   450000  대구
15      한국전력   15760   18000   500000  서울
16   LG디스플레이   34220   19000   300000  서울
17       네이버   35420  360000   550000  성남
18    LG생활건강   51900  900000   150000  서울
19      삼성화재     810  160000   400000  서울

## **1) 데이터 정렬하기**

#### **1. sort_values():** 특정 열의 값을 기준으로 정렬
- by=컬럼명
- ascending : True - 오름차 순, False - 내림차 순
- inplace : 기존 데이터 프레임에 반영 여부

#### **한가지 열을을 기준으로 정렬하기**

In [13]:
# 시리즈 데이터 정렬, 특정 열 정렬하기
df['현재가'].sort_values()

15     18000
16     19000
8      42000
7      45000
10     65000
0      70000
14     85000
1     120000
3     135000
13    150000
19    160000
12    200000
5     200000
9     230000
6     300000
17    360000
2     380000
11    800000
4     800000
18    900000
Name: 현재가, dtype: int64

In [15]:
# sort_values, by=특정열 : 데이터 프레임 정렬, 트정열 기준으로 오름차순 정렬
df.sort_values(by='현재가')

         종목명    종목코드     현재가      거래량  지역
15      한국전력   15760   18000   500000  서울
16   LG디스플레이   34220   19000   300000  서울
8       신한지주   55550   42000   650000  서울
7       KB금융  105560   45000   700000  서울
10     카카오뱅크  323410   65000   450000  서울
0       삼성전자    5930   70000  1000000  서울
14      KT&G   33780   85000   450000  대구
1     SK하이닉스     660  120000   800000  서울
3        카카오   35720  135000   600000  성남
13      LG전자   66570  150000   850000  서울
19      삼성화재     810  160000   400000  서울
12     삼성SDI    6400  200000   250000  서울
5        현대차    5380  200000   400000  울산
9       셀트리온   68270  230000   550000  인천
6      POSCO    5490  300000   200000  포항
17       네이버   35420  360000   550000  성남
2      NAVER   35420  380000   500000  성남
11  삼성바이오로직스  207940  800000   350000  서울
4       LG화학   51910  800000   300000  서울
18    LG생활건강   51900  900000   150000  서울

In [16]:
# ascending=False : 내림차 순으로 정렬하기
df.sort_values(by='현재가', ascending=False)

         종목명    종목코드     현재가      거래량  지역
18    LG생활건강   51900  900000   150000  서울
4       LG화학   51910  800000   300000  서울
11  삼성바이오로직스  207940  800000   350000  서울
2      NAVER   35420  380000   500000  성남
17       네이버   35420  360000   550000  성남
6      POSCO    5490  300000   200000  포항
9       셀트리온   68270  230000   550000  인천
5        현대차    5380  200000   400000  울산
12     삼성SDI    6400  200000   250000  서울
19      삼성화재     810  160000   400000  서울
13      LG전자   66570  150000   850000  서울
3        카카오   35720  135000   600000  성남
1     SK하이닉스     660  120000   800000  서울
14      KT&G   33780   85000   450000  대구
0       삼성전자    5930   70000  1000000  서울
10     카카오뱅크  323410   65000   450000  서울
7       KB금융  105560   45000   700000  서울
8       신한지주   55550   42000   650000  서울
16   LG디스플레이   34220   19000   300000  서울
15      한국전력   15760   18000   500000  서울

#### **여러 열을 기준으로 정렬하기**

In [18]:
# 여러 열을 기준으로 정렬하기 by=[열1, 열2] : 열1로 오름차 순 후 열2로 오름차순 
df.sort_values(by=['종목명', '현재가'])

         종목명    종목코드     현재가      거래량  지역
7       KB금융  105560   45000   700000  서울
14      KT&G   33780   85000   450000  대구
16   LG디스플레이   34220   19000   300000  서울
18    LG생활건강   51900  900000   150000  서울
13      LG전자   66570  150000   850000  서울
4       LG화학   51910  800000   300000  서울
2      NAVER   35420  380000   500000  성남
6      POSCO    5490  300000   200000  포항
1     SK하이닉스     660  120000   800000  서울
17       네이버   35420  360000   550000  성남
12     삼성SDI    6400  200000   250000  서울
11  삼성바이오로직스  207940  800000   350000  서울
0       삼성전자    5930   70000  1000000  서울
19      삼성화재     810  160000   400000  서울
9       셀트리온   68270  230000   550000  인천
8       신한지주   55550   42000   650000  서울
3        카카오   35720  135000   600000  성남
10     카카오뱅크  323410   65000   450000  서울
15      한국전력   15760   18000   500000  서울
5        현대차    5380  200000   400000  울산

In [19]:
#현재가와 지역 기준으로 내림 차순
df.sort_values(by=['종목명', '현재가'], ascending=False )

         종목명    종목코드     현재가      거래량  지역
5        현대차    5380  200000   400000  울산
15      한국전력   15760   18000   500000  서울
10     카카오뱅크  323410   65000   450000  서울
3        카카오   35720  135000   600000  성남
8       신한지주   55550   42000   650000  서울
9       셀트리온   68270  230000   550000  인천
19      삼성화재     810  160000   400000  서울
0       삼성전자    5930   70000  1000000  서울
11  삼성바이오로직스  207940  800000   350000  서울
12     삼성SDI    6400  200000   250000  서울
17       네이버   35420  360000   550000  성남
1     SK하이닉스     660  120000   800000  서울
6      POSCO    5490  300000   200000  포항
2      NAVER   35420  380000   500000  성남
4       LG화학   51910  800000   300000  서울
13      LG전자   66570  150000   850000  서울
18    LG생활건강   51900  900000   150000  서울
16   LG디스플레이   34220   19000   300000  서울
14      KT&G   33780   85000   450000  대구
7       KB금융  105560   45000   700000  서울

In [23]:
#오름차순 내림 차순 혼합 ascending = [True, False,,,,
# 현재가 오름차 순, 거래량는 내림 차순
df.sort_values(by=['현재가', '거래량'], ascending=[True, False] )

         종목명    종목코드     현재가      거래량  지역
15      한국전력   15760   18000   500000  서울
16   LG디스플레이   34220   19000   300000  서울
8       신한지주   55550   42000   650000  서울
7       KB금융  105560   45000   700000  서울
10     카카오뱅크  323410   65000   450000  서울
0       삼성전자    5930   70000  1000000  서울
14      KT&G   33780   85000   450000  대구
1     SK하이닉스     660  120000   800000  서울
3        카카오   35720  135000   600000  성남
13      LG전자   66570  150000   850000  서울
19      삼성화재     810  160000   400000  서울
5        현대차    5380  200000   400000  울산
12     삼성SDI    6400  200000   250000  서울
9       셀트리온   68270  230000   550000  인천
6      POSCO    5490  300000   200000  포항
17       네이버   35420  360000   550000  성남
2      NAVER   35420  380000   500000  성남
11  삼성바이오로직스  207940  800000   350000  서울
4       LG화학   51910  800000   300000  서울
18    LG생활건강   51900  900000   150000  서울

#### **2. sort_index():** 인덱스를 기준으로 정렬
- ascending : True - 오름차 순, False - 내림차 순
- axis=0 (기본값): 행 인덱스를 기준으로 정렬 / axis=1: 열 인덱스를 기준으로 정렬.
- inplace : 기존 데이터 프레임에 반영 여부

In [24]:
# 행 인덱스로 정렬 하기, 기본 오름차 순
df.sort_index()

         종목명    종목코드     현재가      거래량  지역
0       삼성전자    5930   70000  1000000  서울
1     SK하이닉스     660  120000   800000  서울
2      NAVER   35420  380000   500000  성남
3        카카오   35720  135000   600000  성남
4       LG화학   51910  800000   300000  서울
5        현대차    5380  200000   400000  울산
6      POSCO    5490  300000   200000  포항
7       KB금융  105560   45000   700000  서울
8       신한지주   55550   42000   650000  서울
9       셀트리온   68270  230000   550000  인천
10     카카오뱅크  323410   65000   450000  서울
11  삼성바이오로직스  207940  800000   350000  서울
12     삼성SDI    6400  200000   250000  서울
13      LG전자   66570  150000   850000  서울
14      KT&G   33780   85000   450000  대구
15      한국전력   15760   18000   500000  서울
16   LG디스플레이   34220   19000   300000  서울
17       네이버   35420  360000   550000  성남
18    LG생활건강   51900  900000   150000  서울
19      삼성화재     810  160000   400000  서울

In [26]:
# axis=1 열 인덱스로 정렬하기, 열 방향 정렬, 거래량, 종목명...순
df.sort_index(axis=1)

        거래량       종목명    종목코드  지역     현재가
0   1000000      삼성전자    5930  서울   70000
1    800000    SK하이닉스     660  서울  120000
2    500000     NAVER   35420  성남  380000
3    600000       카카오   35720  성남  135000
4    300000      LG화학   51910  서울  800000
5    400000       현대차    5380  울산  200000
6    200000     POSCO    5490  포항  300000
7    700000      KB금융  105560  서울   45000
8    650000      신한지주   55550  서울   42000
9    550000      셀트리온   68270  인천  230000
10   450000     카카오뱅크  323410  서울   65000
11   350000  삼성바이오로직스  207940  서울  800000
12   250000     삼성SDI    6400  서울  200000
13   850000      LG전자   66570  서울  150000
14   450000      KT&G   33780  대구   85000
15   500000      한국전력   15760  서울   18000
16   300000   LG디스플레이   34220  서울   19000
17   550000       네이버   35420  성남  360000
18   150000    LG생활건강   51900  서울  900000
19   400000      삼성화재     810  서울  160000

In [27]:
# 특정열만 추출해서 인덱스로 정렬하기
df['현재가'].sort_index()

0      70000
1     120000
2     380000
3     135000
4     800000
5     200000
6     300000
7      45000
8      42000
9     230000
10     65000
11    800000
12    200000
13    150000
14     85000
15     18000
16     19000
17    360000
18    900000
19    160000
Name: 현재가, dtype: int64

In [28]:
# 여러개 열을 추출해서 인덱스로 정렬하기
df[['현재가','지역']].sort_index(ascending=False)

       현재가  지역
19  160000  서울
18  900000  서울
17  360000  성남
16   19000  서울
15   18000  서울
14   85000  대구
13  150000  서울
12  200000  서울
11  800000  서울
10   65000  서울
9   230000  인천
8    42000  서울
7    45000  서울
6   300000  포항
5   200000  울산
4   800000  서울
3   135000  성남
2   380000  성남
1   120000  서울
0    70000  서울

## **2) 데이터 필터링하기**

### **1. 기본 조건 필터링**

- 단일 조건을 사용하여 특정 열의 값이 주어진 조건을 만족하는 행만 선택할 수 있음
- 불린 데이터와 필터링
    - 불린 데이터는 참(True) 또는 거짓(False) 두 가지 값만을 가짐. 데이터 필터링에서는 각 조건이 불린 값으로 평가되며, True인 경우에만 데이터를 선택함.
- == 같다, != 다르다, >	초과, <	미만, >= 이상, <= 이하

#### **한가지 조건으로 필터하기**

In [29]:
# 조건 연산자로 불린데이터 만들기 
# 현재 주가가 20만원 이상인 데이터의 불린 정보
df['현재가'] >= 200000

0     False
1     False
2      True
3     False
4      True
5      True
6      True
7     False
8     False
9      True
10    False
11     True
12     True
13    False
14    False
15    False
16    False
17     True
18     True
19    False
Name: 현재가, dtype: bool

In [30]:
# 불린 데이터로 행 필터링, 현재 주가가 20만원 이상인 데이터만 필터링
# True 데이터만 필터링 됨
df_filter1 = df[df['현재가']>=200000]
df_filter1

         종목명    종목코드     현재가     거래량  지역
2      NAVER   35420  380000  500000  성남
4       LG화학   51910  800000  300000  서울
5        현대차    5380  200000  400000  울산
6      POSCO    5490  300000  200000  포항
9       셀트리온   68270  230000  550000  인천
11  삼성바이오로직스  207940  800000  350000  서울
12     삼성SDI    6400  200000  250000  서울
17       네이버   35420  360000  550000  성남
18    LG생활건강   51900  900000  150000  서울

In [31]:
# 지역이 서울인 데이터 필터링
df['지역'] == '서울'

0      True
1      True
2     False
3     False
4      True
5     False
6     False
7      True
8      True
9     False
10     True
11     True
12     True
13     True
14    False
15     True
16     True
17    False
18     True
19     True
Name: 지역, dtype: bool

In [32]:
df_seoul = df[df['지역'] == '서울']
df_seoul

         종목명    종목코드     현재가      거래량  지역
0       삼성전자    5930   70000  1000000  서울
1     SK하이닉스     660  120000   800000  서울
4       LG화학   51910  800000   300000  서울
7       KB금융  105560   45000   700000  서울
8       신한지주   55550   42000   650000  서울
10     카카오뱅크  323410   65000   450000  서울
11  삼성바이오로직스  207940  800000   350000  서울
12     삼성SDI    6400  200000   250000  서울
13      LG전자   66570  150000   850000  서울
15      한국전력   15760   18000   500000  서울
16   LG디스플레이   34220   19000   300000  서울
18    LG생활건강   51900  900000   150000  서울
19      삼성화재     810  160000   400000  서울

In [64]:
# 지역이 서울이 아닌 데이터 필터링
df['지역'] != '서울'

0     False
1     False
2      True
3      True
4     False
5      True
6      True
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17     True
18    False
19    False
Name: 지역, dtype: bool

In [65]:
df_filter2 = df['지역'] != '서울'
df_filter2

0     False
1     False
2      True
3      True
4     False
5      True
6      True
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17     True
18    False
19    False
Name: 지역, dtype: bool

#### **여로 조건을 사용한 필터링(AND, OR 조건)**
- 여러 조건을 결합하여 데이터의 필터링을 세분화할 수 있음.
- AND 조건은 & 연산자를 사용하고, OR 조건은 | 연산자를 사용
- 각 조건을 () 괄호로 묶어줌

#### **AND, & : 모두 만족하는 데이터**

In [33]:
# 현재가가 100,000 이상이고 거래량이 500,000 이상인 데이터

# 현재가가 100,000 이상
df[df['현재가'] >= 100000]

         종목명    종목코드     현재가     거래량  지역
1     SK하이닉스     660  120000  800000  서울
2      NAVER   35420  380000  500000  성남
3        카카오   35720  135000  600000  성남
4       LG화학   51910  800000  300000  서울
5        현대차    5380  200000  400000  울산
6      POSCO    5490  300000  200000  포항
9       셀트리온   68270  230000  550000  인천
11  삼성바이오로직스  207940  800000  350000  서울
12     삼성SDI    6400  200000  250000  서울
13      LG전자   66570  150000  850000  서울
17       네이버   35420  360000  550000  성남
18    LG생활건강   51900  900000  150000  서울
19      삼성화재     810  160000  400000  서울

In [34]:
# 거래량이 500,000 이상
df[df['거래량'] >= 500000]

       종목명    종목코드     현재가      거래량  지역
0     삼성전자    5930   70000  1000000  서울
1   SK하이닉스     660  120000   800000  서울
2    NAVER   35420  380000   500000  성남
3      카카오   35720  135000   600000  성남
7     KB금융  105560   45000   700000  서울
8     신한지주   55550   42000   650000  서울
9     셀트리온   68270  230000   550000  인천
13    LG전자   66570  150000   850000  서울
15    한국전력   15760   18000   500000  서울
17     네이버   35420  360000   550000  성남

In [35]:
# 두가지 조건을 모두 만족 : AND 조건은 & 연산자를 사용
df_filter3 = df[(df['현재가'] >= 100000) & (df['거래량'] >= 500000)]
df_filter3

       종목명   종목코드     현재가     거래량  지역
1   SK하이닉스    660  120000  800000  서울
2    NAVER  35420  380000  500000  성남
3      카카오  35720  135000  600000  성남
9     셀트리온  68270  230000  550000  인천
13    LG전자  66570  150000  850000  서울
17     네이버  35420  360000  550000  성남

In [36]:
# 지역이 서울, 거래량이 500,000 이상, 현재가가 50,000원 이상인 데이터
df_filter4 = df[(df['지역'] == '서울') & (df['거래량'] >= 500000) & (df['현재가'] >= 50000)]
df_filter4

       종목명   종목코드     현재가      거래량  지역
0     삼성전자   5930   70000  1000000  서울
1   SK하이닉스    660  120000   800000  서울
13    LG전자  66570  150000   850000  서울

#### **OR, | : 하나라도 만족하는 데이터**

In [37]:
# '현재가'가 100,000 이상이거나 '거래량'이 500,000 이상인 종목 필터링 (OR 조건)
df_filter5 = df[(df['현재가'] >= 100000) | (df['거래량'] >= 500000)]
df_filter5

         종목명    종목코드     현재가      거래량  지역
0       삼성전자    5930   70000  1000000  서울
1     SK하이닉스     660  120000   800000  서울
2      NAVER   35420  380000   500000  성남
3        카카오   35720  135000   600000  성남
4       LG화학   51910  800000   300000  서울
5        현대차    5380  200000   400000  울산
6      POSCO    5490  300000   200000  포항
7       KB금융  105560   45000   700000  서울
8       신한지주   55550   42000   650000  서울
9       셀트리온   68270  230000   550000  인천
11  삼성바이오로직스  207940  800000   350000  서울
12     삼성SDI    6400  200000   250000  서울
13      LG전자   66570  150000   850000  서울
15      한국전력   15760   18000   500000  서울
17       네이버   35420  360000   550000  성남
18    LG생활건강   51900  900000   150000  서울
19      삼성화재     810  160000   400000  서울

In [38]:
# 거래량이 500000이상 이거나 지역이 성남인 데이터
df_filter6 = df[(df['지역'] == '성남') | (df['거래량'] >= 500000)]
df_filter6

       종목명    종목코드     현재가      거래량  지역
0     삼성전자    5930   70000  1000000  서울
1   SK하이닉스     660  120000   800000  서울
2    NAVER   35420  380000   500000  성남
3      카카오   35720  135000   600000  성남
7     KB금융  105560   45000   700000  서울
8     신한지주   55550   42000   650000  서울
9     셀트리온   68270  230000   550000  인천
13    LG전자   66570  150000   850000  서울
15    한국전력   15760   18000   500000  서울
17     네이버   35420  360000   550000  성남

#### **AND OR 혼합해서 쓰기**

In [42]:
# 현재가 100000원 이상 거래량이 500000이상, 또는 지역이 성남인 데이터
df_filter7 = df[(df['지역'] == '성남') | ((df['현재가'] >= 100000) & (df['거래량'] >= 500000))]
df_filter7

       종목명   종목코드     현재가     거래량  지역
1   SK하이닉스    660  120000  800000  서울
2    NAVER  35420  380000  500000  성남
3      카카오  35720  135000  600000  성남
9     셀트리온  68270  230000  550000  인천
13    LG전자  66570  150000  850000  서울
17     네이버  35420  360000  550000  성남

#### **조건 부정, ~ : (NOT 조건)**

In [46]:
# 서울 지역이인 데이터
df[df['지역']=='서울']

         종목명    종목코드     현재가      거래량  지역
0       삼성전자    5930   70000  1000000  서울
1     SK하이닉스     660  120000   800000  서울
4       LG화학   51910  800000   300000  서울
7       KB금융  105560   45000   700000  서울
8       신한지주   55550   42000   650000  서울
10     카카오뱅크  323410   65000   450000  서울
11  삼성바이오로직스  207940  800000   350000  서울
12     삼성SDI    6400  200000   250000  서울
13      LG전자   66570  150000   850000  서울
15      한국전력   15760   18000   500000  서울
16   LG디스플레이   34220   19000   300000  서울
18    LG생활건강   51900  900000   150000  서울
19      삼성화재     810  160000   400000  서울

In [47]:
# 서울 지역이 아닌 데이터
df[df['지역']!='서울']

      종목명   종목코드     현재가     거래량  지역
2   NAVER  35420  380000  500000  성남
3     카카오  35720  135000  600000  성남
5     현대차   5380  200000  400000  울산
6   POSCO   5490  300000  200000  포항
9    셀트리온  68270  230000  550000  인천
14   KT&G  33780   85000  450000  대구
17    네이버  35420  360000  550000  성남

In [49]:
# 서울 지역이 아닌 데이터
# ~를 통해서 True와 False를 바꿈
df[~(df['지역']=='서울')]

      종목명   종목코드     현재가     거래량  지역
2   NAVER  35420  380000  500000  성남
3     카카오  35720  135000  600000  성남
5     현대차   5380  200000  400000  울산
6   POSCO   5490  300000  200000  포항
9    셀트리온  68270  230000  550000  인천
14   KT&G  33780   85000  450000  대구
17    네이버  35420  360000  550000  성남

In [57]:
df_filter7 = df[~(df['지역']=='서울')]
df_filter7

      종목명   종목코드     현재가     거래량  지역
2   NAVER  35420  380000  500000  성남
3     카카오  35720  135000  600000  성남
5     현대차   5380  200000  400000  울산
6   POSCO   5490  300000  200000  포항
9    셀트리온  68270  230000  550000  인천
14   KT&G  33780   85000  450000  대구
17    네이버  35420  360000  550000  성남

### **2. loc[]** : loc[조건, 열 이름]
- 특정 조건을 만족하는 행만을 선택하고, 필요한 열을 함께 선택할 수 있음

In [51]:
df.columns

Index(['종목명', '종목코드', '현재가', '거래량', '지역'], dtype='object')

In [105]:
# 현재가가 200,000 이상인 종목의 종목명, 현재가 열만 필터링
df.loc[df['현재가'] >= 200000, ['종목명', '현재가']]

         종목명     현재가
2      NAVER  380000
4       LG화학  800000
5        현대차  200000
6      POSCO  300000
9       셀트리온  230000
11  삼성바이오로직스  800000
12     삼성SDI  200000
17       네이버  360000
18    LG생활건강  900000

In [59]:
# 복수조건 변수로 설정하기
# '현재가'가 200,000 이상이고 '거래량'이 500,000 이상인 데이터에서 '종목명', '현재가', '거래량' 열 선택
cond1 = (df['현재가'] >= 200000)
cond2 = (df['거래량'] >= 500000)

In [60]:
df_filter = df.loc[cond1 & cond2, ['종목명', '현재가', '거래량']]
df_filter

      종목명     현재가     거래량
2   NAVER  380000  500000
9    셀트리온  230000  550000
17    네이버  360000  550000

In [62]:
#특정열을 선택 후 필터링하기
df[['종목명', '현재가', '거래량']].loc[cond1 & cond2]

      종목명     현재가     거래량
2   NAVER  380000  500000
9    셀트리온  230000  550000
17    네이버  360000  550000

In [63]:
# 행 필터링 후 특정 열 선택하기
df.loc[cond1 & cond2][['종목명', '현재가', '거래량']]

      종목명     현재가     거래량
2   NAVER  380000  500000
9    셀트리온  230000  550000
17    네이버  360000  550000

### **3. 기타**
- isin() : 특정 값들의 목록 중 하나라도 일치하는 데이터만 필터링하는 함수임. 주로 여러 값 중 하나를 선택할 때 사용
- notna() : 결측치가 아닌 값만을 필터링하는 함수임. **결측치(NaN)**가 없는 데이터를 선택할 때 사용
- isnull() : **결측치(NaN)**를 가진 데이터를 필터링하는 함수임. 결측치를 포함하는 행을 필터링
- str.contains() 함수는 문자열 데이터를 필터링할 때 사용되며, 특정 문자열을 포함하는지 여부를 확인
- between(): 두 값 사이의 데이터를 필터링. 숫자나 날짜 범위 필터링

In [69]:
df = pd.read_csv('./pandas_03_DDA2_3.csv', index_col = 0)
df

         종목명      종목코드       현재가        거래량  지역
0       삼성전자    5930.0   70000.0  1000000.0  서울
1     SK하이닉스     660.0  120000.0   800000.0  서울
2      NAVER   35420.0  380000.0   500000.0  성남
3        카카오   35720.0  135000.0   600000.0  성남
4       LG화학       NaN  800000.0   300000.0  서울
5        현대차    5380.0  200000.0   400000.0  울산
6      POSCO    5490.0  300000.0   200000.0  포항
7       KB금융  105560.0   45000.0   700000.0  서울
8       신한지주   55550.0   42000.0   650000.0  서울
9       셀트리온   68270.0  230000.0   550000.0  인천
10     카카오뱅크  323410.0   65000.0   450000.0  서울
11  삼성바이오로직스  207940.0  800000.0   350000.0  서울
12     삼성SDI    6400.0  200000.0   250000.0  서울
13      LG전자   66570.0       NaN   850000.0  서울
14      KT&G   33780.0   85000.0        NaN  대구
15      한국전력   15760.0   18000.0   500000.0  서울
16   LG디스플레이   34220.0   19000.0   300000.0  서울
17       네이버   35420.0  360000.0   550000.0  성남
18    LG생활건강   51900.0       NaN   150000.0  서울
19      삼성화재     810.0  160000.0   400000.0  서울

**isin()** : df [ df['열 이름'].isin([값1, 값2, 값3]) ]

In [79]:
# 찾으려는 값 리스트 
df_filtered = df[df['종목명'].isin(['삼성전자'])]
df_filtered

    종목명    종목코드      현재가        거래량  지역
0  삼성전자  5930.0  70000.0  1000000.0  서울

In [70]:
# 찾으려는 값이 여러개읠 경우 리스트로 
df_filtered = df[df['종목명'].isin(['삼성전자', '카카오', 'LG화학'])]
df_filtered

    종목명     종목코드       현재가        거래량  지역
0  삼성전자   5930.0   70000.0  1000000.0  서울
3   카카오  35720.0  135000.0   600000.0  성남
4  LG화학      NaN  800000.0   300000.0  서울

In [117]:
# 찾으려는 값이 여러개읠 경우 리스트로 
df_filtered = df[df['지역'].isin(['서울', '성남'])]
df_filtered

         종목명    종목코드     현재가      거래량  지역
0       삼성전자  005930   70000  1000000  서울
1     SK하이닉스  000660  120000   800000  서울
2      NAVER  035420  380000   500000  성남
3        카카오  035720  135000   600000  성남
4       LG화학  051910  800000   300000  서울
7       KB금융  105560   45000   700000  서울
8       신한지주  055550   42000   650000  서울
10     카카오뱅크  323410   65000   450000  서울
11  삼성바이오로직스  207940  800000   350000  서울
12     삼성SDI  006400  200000   250000  서울
13      LG전자  066570  150000   850000  서울
15      한국전력  015760   18000   500000  서울
16   LG디스플레이  034220   19000   300000  서울
17       네이버  035420  360000   550000  성남
18    LG생활건강  051900  900000   150000  서울
19      삼성화재  000810  160000   400000  서울

**notna()** : 결측치가 아닌 값만을 필터링하, df[df['열 이름'].notna()] </br>
**isnull()** : **결측치(NaN)**를 가진 데이터를 필터링, df[df['열 이름'].isnull()]

In [80]:
# 현재가가 nan 값이 없는 True 값
df['현재가'].notna()

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13    False
14     True
15     True
16     True
17     True
18    False
19     True
Name: 현재가, dtype: bool

In [82]:
# 현재가가 nan 값이 없는 행 만 출력
df[df['현재가'].notna()]

         종목명      종목코드       현재가        거래량  지역
0       삼성전자    5930.0   70000.0  1000000.0  서울
1     SK하이닉스     660.0  120000.0   800000.0  서울
2      NAVER   35420.0  380000.0   500000.0  성남
3        카카오   35720.0  135000.0   600000.0  성남
4       LG화학       NaN  800000.0   300000.0  서울
5        현대차    5380.0  200000.0   400000.0  울산
6      POSCO    5490.0  300000.0   200000.0  포항
7       KB금융  105560.0   45000.0   700000.0  서울
8       신한지주   55550.0   42000.0   650000.0  서울
9       셀트리온   68270.0  230000.0   550000.0  인천
10     카카오뱅크  323410.0   65000.0   450000.0  서울
11  삼성바이오로직스  207940.0  800000.0   350000.0  서울
12     삼성SDI    6400.0  200000.0   250000.0  서울
14      KT&G   33780.0   85000.0        NaN  대구
15      한국전력   15760.0   18000.0   500000.0  서울
16   LG디스플레이   34220.0   19000.0   300000.0  서울
17       네이버   35420.0  360000.0   550000.0  성남
19      삼성화재     810.0  160000.0   400000.0  서울

In [83]:
# 지역 중 nan 값이 없는 행 만 출력
조건 = df['지역'].notna()
df[조건]

         종목명      종목코드       현재가        거래량  지역
0       삼성전자    5930.0   70000.0  1000000.0  서울
1     SK하이닉스     660.0  120000.0   800000.0  서울
2      NAVER   35420.0  380000.0   500000.0  성남
3        카카오   35720.0  135000.0   600000.0  성남
4       LG화학       NaN  800000.0   300000.0  서울
5        현대차    5380.0  200000.0   400000.0  울산
6      POSCO    5490.0  300000.0   200000.0  포항
7       KB금융  105560.0   45000.0   700000.0  서울
8       신한지주   55550.0   42000.0   650000.0  서울
9       셀트리온   68270.0  230000.0   550000.0  인천
10     카카오뱅크  323410.0   65000.0   450000.0  서울
11  삼성바이오로직스  207940.0  800000.0   350000.0  서울
12     삼성SDI    6400.0  200000.0   250000.0  서울
13      LG전자   66570.0       NaN   850000.0  서울
14      KT&G   33780.0   85000.0        NaN  대구
15      한국전력   15760.0   18000.0   500000.0  서울
16   LG디스플레이   34220.0   19000.0   300000.0  서울
17       네이버   35420.0  360000.0   550000.0  성남
18    LG생활건강   51900.0       NaN   150000.0  서울
19      삼성화재     810.0  160000.0   400000.0  서울

In [ ]:
import numpy as np
# 결측치가 포함된 예제 데이터 생성
data_nan = {
    '종목명': ['삼성전자', 'SK하이닉스', np.nan, '카카오', 'LG화학', '현대차', np.nan, 'KB금융', '신한지주', '셀트리온'],
    '종목코드': ['005930', '000660', '035420', '035720', np.nan, '005380', '005490', np.nan, '055550', '068270'],
    '현재가': [70000, 120000, 380000, np.nan, 800000, 200000, 300000, 45000, np.nan, 230000],
    '거래량': [1000000, 800000, np.nan, 600000, 300000, np.nan, 200000, 700000, 650000, np.nan],
    '지역': ['서울', '서울', '성남', '성남', np.nan, '울산', '포항', '서울', '서울', '인천']
}
df_nan = pd.DataFrame(data_nan)
df_nan

In [11]:
# 현재가가 nan 값인 것만 출력
조건 = df_nan['현재가'].isnull()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8     True
9    False
Name: 현재가, dtype: bool

In [12]:
df_nan[조건]

      종목명    종목코드       현재가        거래량  지역
0    삼성전자  005930   70000.0  1000000.0  서울
1  SK하이닉스  000660  120000.0   800000.0  서울
2     NaN  035420  380000.0        NaN  성남
3     카카오  035720       NaN   600000.0  성남
5     현대차  005380  200000.0        NaN  울산
6     NaN  005490  300000.0   200000.0  포항
7    KB금융     NaN   45000.0   700000.0  서울
8    신한지주  055550       NaN   650000.0  서울
9    셀트리온  068270  230000.0        NaN  인천

**between()** : 두 값 사이에 값을 필터링, 
- df['열 이름'].between(시작 값, 끝 값, inclusive=True)

In [16]:
# 현재가가 100,000 이상 300,000 이하인 데이터
df_nan[df_nan['현재가'].between(100000, 300000)]

      종목명    종목코드       현재가       거래량  지역
1  SK하이닉스  000660  120000.0  800000.0  서울
5   삼성SDS  005380  200000.0       NaN  울산
6     NaN  005490  300000.0  200000.0  포항
9    삼성전기  068270  230000.0       NaN  인천

**str.contains()** :특정 문자열을 포함하는 값 필터링, df[df['열 이름'].str.contains('찾을 문자열')]

In [84]:
# 특정 문자열이 포함되어 있으면 True, 필터링
삼성_df = df[df['종목명'].str.contains('삼성')]
삼성_df

         종목명      종목코드       현재가        거래량  지역
0       삼성전자    5930.0   70000.0  1000000.0  서울
11  삼성바이오로직스  207940.0  800000.0   350000.0  서울
12     삼성SDI    6400.0  200000.0   250000.0  서울
19      삼성화재     810.0  160000.0   400000.0  서울

## **연습문제**

In [88]:
df = pd.read_csv('./pandas_03_DDA2_practice.csv', index_col=0)
df

      종목명    종목코드     현재가  전일대비변동률(%)      거래량  시가총액(억원)   업종
0    삼성전자    5930   70000        -1.5  1000000   4500000   전자
1  SK하이닉스     660  120000         2.0   800000    850000  반도체
2     카카오   35720  135000        -0.8   600000    580000  인터넷
3   NAVER   35420  380000         3.1   500000    550000  인터넷
4    LG화학   51910  800000         1.5   300000   1200000   화학
5     현대차    5380  200000        -2.5   400000    450000  자동차
6   POSCO    5490  300000         0.5   200000    300000   철강
7    KB금융  105560   45000         1.2   700000    320000   금융
8    신한지주   55550   42000         0.7   650000    280000   금융
9    셀트리온   68270  230000        -1.0   550000    480000  바이오

- 종목명: 주식 종목의 이름.
- 종목코드: 종목의 고유 코드.
- 현재가: 종목의 현재 주가.
- 전일대비변동률(%): 전일 종가 대비 당일 주가 변동률.
- 거래량: 하루 동안 거래된 주식의 수.
- 시가총액(억원): 종목의 총 시가총액.
- 업종: 종목이 속한 산업군 (예: 전자, 반도체, 인터넷 등)

**연습 문제 1: 데이터 탐색**
- 1) 데이터프레임의 구조를 확인하기 위해, 전체 데이터의 첫 5개 행을 출력하시오.
- 2) **iloc[]**를 사용하여 첫 3개의 열과 첫 4개의 행을 선택하여 데이터를 출력하시오.
- 3) 종목명, 현재가, 전일대비변동률(%) 만 출력하여 첫 5개의 행을 확인하시오.

In [89]:
# 1. 상위 5개 행 출력
df.head(5)

      종목명   종목코드     현재가  전일대비변동률(%)      거래량  시가총액(억원)   업종
0    삼성전자   5930   70000        -1.5  1000000   4500000   전자
1  SK하이닉스    660  120000         2.0   800000    850000  반도체
2     카카오  35720  135000        -0.8   600000    580000  인터넷
3   NAVER  35420  380000         3.1   500000    550000  인터넷
4    LG화학  51910  800000         1.5   300000   1200000   화학

In [90]:
# 2. 첫 4개행과 첫 3개열
df.iloc[:4, :3]

      종목명   종목코드     현재가
0    삼성전자   5930   70000
1  SK하이닉스    660  120000
2     카카오  35720  135000
3   NAVER  35420  380000

In [91]:
# 3. 종목명, 현재가, 전일대비변동률(%) 만 출력하여 첫 5개의 행
df[['종목명', '현재가', '전일대비변동률(%)']].head(5)

      종목명     현재가  전일대비변동률(%)
0    삼성전자   70000        -1.5
1  SK하이닉스  120000         2.0
2     카카오  135000        -0.8
3   NAVER  380000         3.1
4    LG화학  800000         1.5

**연습 문제 2: 데이터 필터링**
- 1) **전일대비변동률이 양수(+)** 인 종목을 필터링하고, **'종목명', '전일대비변동률(%)'** 만 출력하시오.
- 2) 전일대비변동률이 1% 이상이고, 거래량이 500,000 이상인 종목을 필터링하시오.
- 3) 업종이 **'금융'**인 종목을 필터링하고, **'종목명', '업종', '현재가'** 를 출력하시오.

In [104]:
# 1. 전일대비변동률이 양수(+)**인 종목을 필터링하고, **'종목명', '전일대비변동률(%)'**만 출력
df_filtered = df[df['전일대비변동률(%)'] > 0]
df_filtered[['종목명', '전일대비변동률(%)']]

      종목명  전일대비변동률(%)
1  SK하이닉스         2.0
3   NAVER         3.1
4    LG화학         1.5
6   POSCO         0.5
7    KB금융         1.2
8    신한지주         0.7

In [103]:
df_filtered1 = df[df['전일대비변동률(%)'] > 0][['종목명', '전일대비변동률(%)']]
df_filtered1

      종목명  전일대비변동률(%)
1  SK하이닉스         2.0
3   NAVER         3.1
4    LG화학         1.5
6   POSCO         0.5
7    KB금융         1.2
8    신한지주         0.7

In [100]:
# loc 활용하기
cond1 = (df['전일대비변동률(%)'] > 0)
df.loc[cond1, ['종목명', '전일대비변동률(%)']]

      종목명  전일대비변동률(%)
1  SK하이닉스         2.0
3   NAVER         3.1
4    LG화학         1.5
6   POSCO         0.5
7    KB금융         1.2
8    신한지주         0.7

In [105]:
# 2. 전일대비변동률이 1% 이상이고, 거래량이 500,000 이상인 종목을 필터
df_filtered3 = df[(df['전일대비변동률(%)'] >= 1) & (df['거래량'] >= 500000)]
df_filtered3

      종목명    종목코드     현재가  전일대비변동률(%)     거래량  시가총액(억원)   업종
1  SK하이닉스     660  120000         2.0  800000    850000  반도체
3   NAVER   35420  380000         3.1  500000    550000  인터넷
7    KB금융  105560   45000         1.2  700000    320000   금융

In [106]:
# 3. 업종이 '금융'인 종목을 필터링하고, '종목명', '업종', '현재가'를 출력
df_filtered = df[df['업종'] == '금융']
df_filtered[['종목명', '업종', '현재가']]

    종목명  업종    현재가
7  KB금융  금융  45000
8  신한지주  금융  42000

**연습 문제 3**
- 1) 전일대비변동률이 0.5% 이상이고, 거래량이 400,000 이상인 종목을 필터링한 후, 거래량을 기준으로 내림차순 정렬하시오.
- 2) 시가총액이 500,000억원 이상인 종목 중, **'현재가'**가 200,000 이상인 종목을 필터링하고, 현재가 기준으로 내림차순 정렬하시오.
- 3) **업종이 '인터넷'**인 종목 중에서 현재가가 200,000 이상인 종목을 필터링하고, 전일대비변동률(%) 기준으로 내림차순 정렬하시오.

In [49]:
# 1. 전일대비변동률이 0.5% 이상이고, 거래량이 400,000 이상인 종목을 필터링한 후, 거래량을 기준으로 내림차순 정렬
df_filtered_sorted = df[(df['전일대비변동률(%)'] >= 0.5) & (df['거래량'] >= 400000)]
df_filtered_sorted = df_filtered_sorted.sort_values(by='거래량', ascending=False)
df_filtered_sorted

      종목명    종목코드     현재가  전일대비변동률(%)     거래량  시가총액(억원)   업종
1  SK하이닉스  000660  120000         2.0  800000    850000  반도체
7    KB금융  105560   45000         1.2  700000    320000   금융
8    신한지주  055550   42000         0.7  650000    280000   금융
3   NAVER  035420  380000         3.1  500000    550000  인터넷

In [50]:
# 2. 시가총액이 500,000억원 이상인 종목 중, **'현재가'**가 200,000 이상인 종목을 필터링하고, 현재가 기준으로 내림차순 정렬
df_filtered_sorted = df[(df['시가총액(억원)'] >= 500000) & (df['현재가'] >= 200000)]
df_filtered_sorted = df_filtered_sorted.sort_values(by='현재가', ascending=False)
df_filtered_sorted

     종목명    종목코드     현재가  전일대비변동률(%)     거래량  시가총액(억원)   업종
4   LG화학  051910  800000         1.5  300000   1200000   화학
3  NAVER  035420  380000         3.1  500000    550000  인터넷

In [51]:
# 3. 업종이 '인터넷'**인 종목 중에서 현재가가 200,000 이상인 종목을 필터링하고, 전일대비변동률(%) 기준으로 내림차순 정렬
df_filtered_sorted = df[(df['업종'] == '인터넷') & (df['현재가'] >= 200000)]
df_filtered_sorted = df_filtered_sorted.sort_values(by='전일대비변동률(%)', ascending=False)
df_filtered_sorted

     종목명    종목코드     현재가  전일대비변동률(%)     거래량  시가총액(억원)   업종
3  NAVER  035420  380000         3.1  500000    550000  인터넷