In [2]:
import pandas as pd

## **1) Series**
- index(순서)와 value(값)로 구성되어 있음
- 1차원 데이터를 다루는 구조임. 인덱스와 값으로 이루어져 있으며, 엑셀의 한 열과 유사함.
- 각 값에 고유한 인덱스가 있어, 데이터를 쉽게 조회하거나 연산할 수 있음.

### **Series 생성 방법**
- pd.Series()를 사용하여 생성 가능함.

#### **1. 리스트로 Series 생성**
- 리스트를 이용해 Series를 생성할 수 있음. 인덱스를 명시하지 않으면 기본적으로 0부터 시작하는 숫자가 인덱스로 자동 설정됨.

In [8]:
# 리스트로 Series 생성
매출액 = pd.Series([1500, 2000, 2500, 3000, 3500, 4000])
매출액

0    1500
1    2000
2    2500
3    3000
4    3500
5    4000
dtype: int64

#### **리스트 + 인덱스 지정**
- 리스트 외에도, 인덱스를 직접 지정하여 Series를 생성할 수 있음

In [11]:
# 리스트와 인덱스 지정하여 Series 생성
매출액 = pd.Series([1500, 2000, 2500, 3000, 3500, 4000], index=['1월', '2월', '3월', '4월', '5월', '6월'])
매출액

1월    1500
2월    2000
3월    2500
4월    3000
5월    3500
6월    4000
dtype: int64

#### **딕셔너리로 Series 생성**
- 딕셔너리 데이터 구조도 Series로 변환할 수 있음. 이 경우, 딕셔너리의 키가 인덱스가 되고, 값이 Series의 데이터가 됨.

In [14]:
# 딕셔너리로 Series 생성
매출액 = pd.Series({'1월': 1500,
                 '2월': 2000,
                 '3월': 2500,
                 '4월': 3000,
                 '5월': 3500,
                 '6월': 4000,})
매출액

1월    1500
2월    2000
3월    2500
4월    3000
5월    3500
6월    4000
dtype: int64

#### **넘파이 배열로 Series 생성**
- 넘파이 배열을 사용하여 Series를 만들 수 있으며, 넘파이 배열은 대용량 데이터 처리에 적합함.

In [16]:
import numpy as np

# 넘파이 배열로 Series 생성
매출액 = pd.Series(np.array([1500, 2000, 2500, 3000, 3500, 4000]))
매출액

0    1500
1    2000
2    2500
3    3000
4    3500
5    4000
dtype: int32

#### **Series 데이터 통계 지표**
- sum() : 합계
- mean() : 평균
- median() : 중앙값
- min() 최소값, max() 최댓값

In [68]:
print(매출액.sum())
print(매출액.mean())
print(매출액.median())
print(매출액.min(), 매출액.max())

16500
2750.0
2750.0
1500 4000

## **2) DataFrame**
- DataFrame은 판다스의 2차원 데이터 구조로, 행과 열로 이루어진 데이터 프레임임.
- 엑셀의 표와 유사한 구조로, 여러 개의 Series가 모여 행(row)과 열(column)을 이루 며 데이터를 구성함
- index(순서), column(속성), value(값)로 구성되어 있음

#### **1.딕셔너리로 DataFrame 생성**
- 딕셔너리를 사용하여 쉽게 DataFrame을 생성할 수 있음. 딕셔너리의 키는 열(column) 이름이 되고, 각 값은 해당 열의 데이터가 됨.

In [18]:
# 딕셔너리로 DataFrame 생성
데이터 = {
    '상품명': ['A제품', 'B제품', 'C제품', 'D제품'],
    '매출액': [1500, 2000, 2500, 3000],
    '판매수량': [100, 150, 200, 250]
}

df = pd.DataFrame(데이터)
df

   상품명   매출액  판매수량
0  A제품  1500   100
1  B제품  2000   150
2  C제품  2500   200
3  D제품  3000   250

#### **리스트로 DataFrame 생성**
- 리스트의 리스트 구조를 사용하여 DataFrame을 생성할 수 있음. 각 내부 리스트는 하나의 행(row)을 나타냄.

In [21]:
# 리스트로 DataFrame 생성
df2 = pd.DataFrame([
    ['A제품', 1500, 100],
    ['B제품', 2000, 150],
    ['C제품', 2500, 200],
    ['D제품', 3000, 250]
], columns=['상품명', '매출액', '판매수량'])

df2

   상품명   매출액  판매수량
0  A제품  1500   100
1  B제품  2000   150
2  C제품  2500   200
3  D제품  3000   250

### **DataFrame 다루기**

In [3]:
# DataFrame 생성
data = {
    '종목명': ['삼성전자', 'SK하이닉스', 'NAVER', '카카오', 'LG화학',],
    '종목코드': ['005930', '000660', '035420', '035720', '051910'],
    '현재가': [70000, 120000, 380000, 135000, 800000],
    '거래량': [1000000, 800000, 500000, 600000, 300000],
    '지역': ['서울', '서울', '성남', '성남', '서울']
}

df = pd.DataFrame(data)

#### **set_index()** : 특정 열을 인덱스로 설정하는 데 사용됨. 
- 인덱스는 행의 식별자 역할을 하며, 데이터 조작 및 조회에 중요한 역할을 함.
- set_index('열이름'): 지정한 열을 인덱스로 설정.
- drop=False: 인덱스로 설정한 열을 데이터프레임에서 삭제하지 않고 유지.
- inplace=True: 원본 데이터프레임에 바로 적용

In [8]:
# '종목코드'를 인덱스로 설정 (drop=False)
df_with_index = df.set_index('종목코드', drop=False)
df_with_index

           종목명    종목코드     현재가      거래량  지역
종목코드
005930    삼성전자  005930   70000  1000000  서울
000660  SK하이닉스  000660  120000   800000  서울
035420   NAVER  035420  380000   500000  성남
035720     카카오  035720  135000   600000  성남
051910    LG화학  051910  800000   300000  서울

In [9]:
# '종목코드'를 인덱스로 설정 (drop=True)
df_with_index2 = df.set_index('종목코드', drop=True)
df_with_index2

           종목명     현재가      거래량  지역
종목코드
005930    삼성전자   70000  1000000  서울
000660  SK하이닉스  120000   800000  서울
035420   NAVER  380000   500000  성남
035720     카카오  135000   600000  성남
051910    LG화학  800000   300000  서울

In [14]:
# 기존 데이터 프레임에 반영하기
df.set_index('종목코드', drop=True, inplace=True)
df

           회사명      가격      거래량  지역
종목코드
005930    삼성전자   70000  1000000  서울
000660  SK하이닉스  120000   800000  서울
035420   NAVER  380000   500000  성남
035720     카카오  135000   600000  성남
051910    LG화학  800000   300000  서울

#### **reset_index()** 
- : 인덱스를 기본값(정수형 인덱스)으로 되돌리는 데 사용됨. 기존 인덱스는 열로 변환되고, 정수형 인덱스가 새로 부여됨.
- drop=True: 기존 인덱스를 열로 변환하지 않고 제거.
- inplace=True: 원본 데이터프레임에 바로 적용.

In [18]:
# index열 열로 전환
df.reset_index(inplace=True)

# index열 삭제
# df.reset_index(inplace=True, drop=True)

df

     종목코드     회사명      가격      거래량  지역
0  005930    삼성전자   70000  1000000  서울
1  000660  SK하이닉스  120000   800000  서울
2  035420   NAVER  380000   500000  성남
3  035720     카카오  135000   600000  성남
4  051910    LG화학  800000   300000  서울

#### **rename(): 행 또는 열 이름 변경**
- 데이터프레임의 행 인덱스 또는 열 이름을 변경할 때 사용됨. **딕셔너리**를 사용하여 원하는 이름으로 변경할 수 있음
- columns={'old_name': 'new_name'}: 열 이름을 변경.
- index={'old_name': 'new_name'}: 행 이름(인덱스)을 변경.
- inplace=True: 원본 데이터프레임에 바로 적용

In [19]:
df.set_index('종목코드', drop=True, inplace=True)
df

           회사명      가격      거래량  지역
종목코드
005930    삼성전자   70000  1000000  서울
000660  SK하이닉스  120000   800000  서울
035420   NAVER  380000   500000  성남
035720     카카오  135000   600000  성남
051910    LG화학  800000   300000  서울

In [ ]:
# 열 이름 변경
df.rename(columns={'종목명': '회사명', '현재가': '가격'}, inplace=True)
df

In [20]:
# 행 인덱스(종목코드) 이름 변경
df.rename(index={'005930': '삼성전자', '000660': 'SK하이닉스'}, inplace=True)
df

           회사명      가격      거래량  지역
종목코드
삼성전자      삼성전자   70000  1000000  서울
SK하이닉스  SK하이닉스  120000   800000  서울
035420   NAVER  380000   500000  성남
035720     카카오  135000   600000  성남
051910    LG화학  800000   300000  서울

#### **drop(): 행 또는 열 삭제**
- axis=0: 행을 삭제.
- axis=1: 열을 삭제.
- inplace=True: 원본 데이터프레임에 바로 적용

In [21]:
# 회사명 열 삭제
df2 = df.drop('회사명', axis=1)
df2

            가격      거래량  지역
종목코드
삼성전자     70000  1000000  서울
SK하이닉스  120000   800000  서울
035420  380000   500000  성남
035720  135000   600000  성남
051910  800000   300000  서울

In [22]:
# 종목코드 SK하이닉스, 삼성전자 삭제
df3 = df.drop(labels=['SK하이닉스','삼성전자'] , axis=0)
df3

          회사명      가격     거래량  지역
종목코드
035420  NAVER  380000  500000  성남
035720    카카오  135000  600000  성남
051910   LG화학  800000  300000  서울

### **3) 데이터 로드 및 저장**
- 데이터 로드해서 DataFrame을 만들 수 있음
- CSV나 Excel 파일로부터 데이터를 불러오거나 저장할 수 있음
    - read_csv(), read_excel(): 파일에서 데이터를 불러옴.
    - to_csv(), to_excel(): 데이터를 파일로 저장함.

In [40]:
# pd.read_csv('파일경로.csv')
df = pd.read_csv('./01_Contract_Data.csv')
df

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,5.0,농협회원조합
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,개인,47.0,경기도,경기도,계약확정,0,없음,남자,NaN,기업은행
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,8.0,새마을금고
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,개인,54.0,서울특별시,서울특별시,계약확정,0,없음,여자,2.0,롯데카드
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,개인,53.0,서울특별시,서울특별시,계약확정,0,없음,여자,8.0,신한은행

#### **한글 인코딩 파일**
- encoding: 파일의 인코딩 방식을 지정함. 
- 한글이 포함된 파일을 읽을 때는 **utf-8** / **euc-kr**/**cp949** 설정

In [46]:
# 한글 인코딩 문제 해결 (UTF-8 또는 EUC-KR)
df = pd.read_csv('./pandas_02.csv', encoding='euc-kr')
df

   Unnamed: 0     종목명    종목코드     현재가      거래량  지역
0           0    삼성전자    5930   70000  1000000  서울
1           1  SK하이닉스     660  120000   800000  서울
2           2   NAVER   35420  380000   500000  성남
3           3     카카오   35720  135000   600000  성남
4           4    LG화학   51910  800000   300000  서울
5           5     현대차    5380  200000   400000  울산
6           6   POSCO    5490  300000   200000  포항
7           7    KB금융  105560   45000   700000  서울
8           8    신한지주   55550   42000   650000  서울
9           9    셀트리온   68270  230000   550000  인천

#### **index아 header 설정**
- **header:**
    - CSV 파일의 첫 번째 행을 열 이름으로 사용할지 여부를 지정함.
    - 기본값은 header=0으로, 첫 번째 행을 열 이름으로 사용
    - CSV 파일에 열 이름이 없으면 header=None으로 설정하고 열 이름을 직접 지정할 수 있음.
- **index_col :**
    - 특정 열을 DataFrame의 인덱스로 지정함. 인덱스로 사용할 열의 이름이나 번호를 지정할 수 있음.

#### **특정열 특정행만 가져오기**
- usecols: 특정 열만 선택해서 읽을 수 있음
- skiprows: 파일의 처음 몇 개의 행을 건너뜀
- nrows: 파일에서 처음 몇 개의 행만 읽고 싶은 경우

In [54]:
# index_col 첫번째 열을 인덱스로 설정하기
df = pd.read_csv('./pandas_02.csv', encoding='euc-kr', index_col=0)
df

      종목명    종목코드     현재가      거래량  지역
0    삼성전자    5930   70000  1000000  서울
1  SK하이닉스     660  120000   800000  서울
2   NAVER   35420  380000   500000  성남
3     카카오   35720  135000   600000  성남
4    LG화학   51910  800000   300000  서울
5     현대차    5380  200000   400000  울산
6   POSCO    5490  300000   200000  포항
7    KB금융  105560   45000   700000  서울
8    신한지주   55550   42000   650000  서울
9    셀트리온   68270  230000   550000  인천

In [55]:
# name 컬럼명 설정하기
df = pd.read_csv('./pandas_02.csv', encoding='euc-kr',index_col=0, names=['회사명', '티커', '가격', '거래량', '지역'])
df

        회사명      티커      가격      거래량  지역
NaN     종목명    종목코드     현재가      거래량  지역
0.0    삼성전자  005930   70000  1000000  서울
1.0  SK하이닉스  000660  120000   800000  서울
2.0   NAVER  035420  380000   500000  성남
3.0     카카오  035720  135000   600000  성남
4.0    LG화학  051910  800000   300000  서울
5.0     현대차  005380  200000   400000  울산
6.0   POSCO  005490  300000   200000  포항
7.0    KB금융  105560   45000   700000  서울
8.0    신한지주  055550   42000   650000  서울
9.0    셀트리온  068270  230000   550000  인천

In [58]:
# skiprows 행 1개 건너띄고 가져오기
df = pd.read_csv('./pandas_02.csv', encoding='euc-kr',index_col=0,\
                 names=['회사명', '티커', '가격', '거래량', '지역'], skiprows=1)
df

      회사명      티커      가격      거래량  지역
0    삼성전자    5930   70000  1000000  서울
1  SK하이닉스     660  120000   800000  서울
2   NAVER   35420  380000   500000  성남
3     카카오   35720  135000   600000  성남
4    LG화학   51910  800000   300000  서울
5     현대차    5380  200000   400000  울산
6   POSCO    5490  300000   200000  포항
7    KB금융  105560   45000   700000  서울
8    신한지주   55550   42000   650000  서울
9    셀트리온   68270  230000   550000  인천

In [61]:
df = pd.read_csv('./pandas_02.csv', encoding='cp949', index_col=0)
df

      종목명    종목코드     현재가      거래량  지역
0    삼성전자    5930   70000  1000000  서울
1  SK하이닉스     660  120000   800000  서울
2   NAVER   35420  380000   500000  성남
3     카카오   35720  135000   600000  성남
4    LG화학   51910  800000   300000  서울
5     현대차    5380  200000   400000  울산
6   POSCO    5490  300000   200000  포항
7    KB금융  105560   45000   700000  서울
8    신한지주   55550   42000   650000  서울
9    셀트리온   68270  230000   550000  인천

In [63]:
# usecols 특정 열만 선택해서 읽기
df = pd.read_csv('./pandas_02.csv', encoding='cp949',\
                 index_col=0, usecols=['종목명', '현재가', '지역'])
df

           현재가  지역
종목명
삼성전자     70000  서울
SK하이닉스  120000  서울
NAVER   380000  성남
카카오     135000  성남
LG화학    800000  서울
현대차     200000  울산
POSCO   300000  포항
KB금융     45000  서울
신한지주     42000  서울
셀트리온    230000  인천

In [65]:
# nrows 처음 5개 행만 가져오기
df = pd.read_csv('./pandas_02.csv', encoding='cp949', index_col=0, nrows=5)
df

      종목명   종목코드     현재가      거래량  지역
0    삼성전자   5930   70000  1000000  서울
1  SK하이닉스    660  120000   800000  서울
2   NAVER  35420  380000   500000  성남
3     카카오  35720  135000   600000  성남
4    LG화학  51910  800000   300000  서울

In [69]:
# skiprows, nrows 혼합, 11~20번째 행까지만 가져오기
df = pd.read_csv('./pandas_02.csv', encoding='cp949', index_col=0, skiprows=5, nrows=5)
df

    LG화학  051910  800000  300000  서울
4
5    현대차    5380  200000  400000  울산
6  POSCO    5490  300000  200000  포항
7   KB금융  105560   45000  700000  서울
8   신한지주   55550   42000  650000  서울
9   셀트리온   68270  230000  550000  인천

## **3) 데이터 프레임 다루기 2**

### **1. 열 선택**
- 데이터프레임에서 특정 **열(column)**을 열 이름을 사용하여 열을 추출하는 것임.
- 여러 개의 열을 동시에 선택할 때는 열 이름을 리스트 추출.

In [70]:
# 데이터 불러오기
df = pd.read_csv('./pandas_02.csv', encoding='cp949', index_col=0)
df

      종목명    종목코드     현재가      거래량  지역
0    삼성전자    5930   70000  1000000  서울
1  SK하이닉스     660  120000   800000  서울
2   NAVER   35420  380000   500000  성남
3     카카오   35720  135000   600000  성남
4    LG화학   51910  800000   300000  서울
5     현대차    5380  200000   400000  울산
6   POSCO    5490  300000   200000  포항
7    KB금융  105560   45000   700000  서울
8    신한지주   55550   42000   650000  서울
9    셀트리온   68270  230000   550000  인천

In [71]:
# 열이름으로 인덱싱하기 - 1개열 추출 / 시리즈 타입으로 출력
df['종목명']

0      삼성전자
1    SK하이닉스
2     NAVER
3       카카오
4      LG화학
5       현대차
6     POSCO
7      KB금융
8      신한지주
9      셀트리온
Name: 종목명, dtype: object

In [72]:
# 열이름으로 인덱싱 - 1개열 데이터 프레임으로 출력
df[['종목명']]

      종목명
0    삼성전자
1  SK하이닉스
2   NAVER
3     카카오
4    LG화학
5     현대차
6   POSCO
7    KB금융
8    신한지주
9    셀트리온

In [73]:
# 열이름으로 인덱싱 - 복수개의 열 추출
# 2개의 이상의 열은 index_column_value로 이루어져 있기 때문에 Series로 출력을 못함
df['종목명', '현재가', '지역']

KeyError: ('종목명', '현재가', '지역')

In [74]:
# 열이름으로 인덱싱 - 복수개의 열 추출
df[['종목명', '현재가', '지역']]

      종목명     현재가  지역
0    삼성전자   70000  서울
1  SK하이닉스  120000  서울
2   NAVER  380000  성남
3     카카오  135000  성남
4    LG화학  800000  서울
5     현대차  200000  울산
6   POSCO  300000  포항
7    KB금융   45000  서울
8    신한지주   42000  서울
9    셀트리온  230000  인천

### **2. 행 선택**
- head() : 상위 행 선택
- tail() : 하위 행 선택
- sample() : 랜덤 추출

In [75]:
# head() : 상위 5개 행 데이터 추출
df.head()

      종목명   종목코드     현재가      거래량  지역
0    삼성전자   5930   70000  1000000  서울
1  SK하이닉스    660  120000   800000  서울
2   NAVER  35420  380000   500000  성남
3     카카오  35720  135000   600000  성남
4    LG화학  51910  800000   300000  서울

In [80]:
# 상위 50개 행 추출할 경우
df.head(10)

      종목명    종목코드     현재가      거래량  지역
0    삼성전자    5930   70000  1000000  서울
1  SK하이닉스     660  120000   800000  서울
2   NAVER   35420  380000   500000  성남
3     카카오   35720  135000   600000  성남
4    LG화학   51910  800000   300000  서울
5     현대차    5380  200000   400000  울산
6   POSCO    5490  300000   200000  포항
7    KB금융  105560   45000   700000  서울
8    신한지주   55550   42000   650000  서울
9    셀트리온   68270  230000   550000  인천

In [77]:
# tail() : 하위 5개 행 데이터 추출
df.tail()

     종목명    종목코드     현재가     거래량  지역
5    현대차    5380  200000  400000  울산
6  POSCO    5490  300000  200000  포항
7   KB금융  105560   45000  700000  서울
8   신한지주   55550   42000  650000  서울
9   셀트리온   68270  230000  550000  인천

In [79]:
# 하위 50개 행 추출할 경우
df.tail(10)

      종목명    종목코드     현재가      거래량  지역
0    삼성전자    5930   70000  1000000  서울
1  SK하이닉스     660  120000   800000  서울
2   NAVER   35420  380000   500000  성남
3     카카오   35720  135000   600000  성남
4    LG화학   51910  800000   300000  서울
5     현대차    5380  200000   400000  울산
6   POSCO    5490  300000   200000  포항
7    KB금융  105560   45000   700000  서울
8    신한지주   55550   42000   650000  서울
9    셀트리온   68270  230000   550000  인천

In [81]:
# sample() : 랜덤하게 데이터를 추출하므로, 샘플링이나 무작위로 데이터를 확인할 때 유용함
df.sample(3)

    종목명    종목코드     현재가     거래량  지역
4  LG화학   51910  800000  300000  서울
5   현대차    5380  200000  400000  울산
7  KB금융  105560   45000  700000  서울

#### **행열 혼합해서 쓰기**

In [82]:
# 혼합해서 쓰기, 두개의 열을 선택하고 상위 5개 출력
df[['종목명','현재가']].head()

      종목명     현재가
0    삼성전자   70000
1  SK하이닉스  120000
2   NAVER  380000
3     카카오  135000
4    LG화학  800000

In [83]:
# 상위 행 5개 선택하고, 2개의 열 출력
df.head()[['종목명', '현재가']]

      종목명     현재가
0    삼성전자   70000
1  SK하이닉스  120000
2   NAVER  380000
3     카카오  135000
4    LG화학  800000

### **3. iloc[]와 loc[]**
- 1. iloc[]: 숫자 인덱스(정수 위치) 사용하여 데이터프레임의 특정 위치에 있는 행과 열을 선택하는 방식임
- 2. loc[]는 인덱스 이름 또는 열 이름을 사용하여 데이터를 선택하는 방식임. 즉, 행과 열의 이름(레이블) 사용

#### **사용법 iloc[행위치 , 열위치]** 
-  iloc[row_index, column_index]
-  start : end : step

In [84]:
# iloc[] : 첫번째 행 출력하기
df.iloc[0] # 첫번째 행 출력

종목명        삼성전자
종목코드       5930
현재가       70000
거래량     1000000
지역           서울
Name: 0, dtype: object

In [85]:
# 세번째 행 출력
df.iloc[2]

종목명      NAVER
종목코드     35420
현재가     380000
거래량     500000
지역          성남
Name: 2, dtype: object

In [90]:
# 첫번째 부터 5번째 행까지 출력
df.iloc[0:5] # 0은 생략 가능
# df.iloc[:5]

      종목명   종목코드     현재가      거래량  지역
0    삼성전자   5930   70000  1000000  서울
1  SK하이닉스    660  120000   800000  서울
2   NAVER  35420  380000   500000  성남
3     카카오  35720  135000   600000  성남
4    LG화학  51910  800000   300000  서울

In [89]:
# 10번째 행까지 출력, 2step씩 출력
df.iloc[:10:2]

     종목명   종목코드     현재가      거래량  지역
0   삼성전자   5930   70000  1000000  서울
2  NAVER  35420  380000   500000  성남
4   LG화학  51910  800000   300000  서울
6  POSCO   5490  300000   200000  포항
8   신한지주  55550   42000   650000  서울

In [92]:
# 5행 부터 끝까지 출력
df.iloc[5:]

     종목명    종목코드     현재가     거래량  지역
5    현대차    5380  200000  400000  울산
6  POSCO    5490  300000  200000  포항
7   KB금융  105560   45000  700000  서울
8   신한지주   55550   42000  650000  서울
9   셀트리온   68270  230000  550000  인천

In [94]:
# 3행부터 마지막에서 두번째 행까지 출력
df.iloc[2:-2]

     종목명    종목코드     현재가     거래량  지역
2  NAVER   35420  380000  500000  성남
3    카카오   35720  135000  600000  성남
4   LG화학   51910  800000  300000  서울
5    현대차    5380  200000  400000  울산
6  POSCO    5490  300000  200000  포항
7   KB금융  105560   45000  700000  서울

### 사용법 **loc[]** 
- 인덱스 이름 또는 열 이름을 사용하여 데이터를 선택하는 방식임. 
- 행과 열을 선택할 때 정수 인덱스가 아니라 **이름(레이블)**을 사용
- **loc[행 인덱스 이름, 열 인덱스 이름]**
- **start : end : step**

In [99]:
# 종목명 열로 인덱스 재 설정, 기존 열 삭제
df2 = df.set_index('종목명', drop=True)
df2

          종목코드     현재가      거래량  지역
종목명
삼성전자      5930   70000  1000000  서울
SK하이닉스     660  120000   800000  서울
NAVER    35420  380000   500000  성남
카카오      35720  135000   600000  성남
LG화학     51910  800000   300000  서울
현대차       5380  200000   400000  울산
POSCO     5490  300000   200000  포항
KB금융    105560   45000   700000  서울
신한지주     55550   42000   650000  서울
셀트리온     68270  230000   550000  인천

In [101]:
# 특정 행 선택, 행 인덱스 이름으로 인덱싱
df2.loc['삼성전자']

종목코드       5930
현재가       70000
거래량     1000000
지역           서울
Name: 삼성전자, dtype: object

In [103]:
# 여러행 선택, 떨어져 있는 행
df2.loc[['삼성전자', 'NAVER']]

        종목코드     현재가      거래량  지역
종목명
삼성전자    5930   70000  1000000  서울
NAVER  35420  380000   500000  성남

In [104]:
# 여러행 선택 : 연속되는 여러행 선택
df2.loc['삼성전자':'현대차']

         종목코드     현재가      거래량  지역
종목명
삼성전자     5930   70000  1000000  서울
SK하이닉스    660  120000   800000  서울
NAVER   35420  380000   500000  성남
카카오     35720  135000   600000  성남
LG화학    51910  800000   300000  서울
현대차      5380  200000   400000  울산

In [109]:
# 모든행의 특정 열 선택, 인덱스도 함게 출력
df2.loc[:, '지역']

종목명
삼성전자      서울
SK하이닉스    서울
NAVER     성남
카카오       성남
LG화학      서울
현대차       울산
POSCO     포항
KB금융      서울
신한지주      서울
셀트리온      인천
Name: 지역, dtype: object

In [110]:
# 모든행의 복수의 열 선택 - 떨어져 있는
df2.loc[:, ['현재가','지역']]

           현재가  지역
종목명
삼성전자     70000  서울
SK하이닉스  120000  서울
NAVER   380000  성남
카카오     135000  성남
LG화학    800000  서울
현대차     200000  울산
POSCO   300000  포항
KB금융     45000  서울
신한지주     42000  서울
셀트리온    230000  인천

In [111]:
# 모든행의 복수의 열 선택 - 연속되는
df2.loc[:, '현재가':'지역']

           현재가      거래량  지역
종목명
삼성전자     70000  1000000  서울
SK하이닉스  120000   800000  서울
NAVER   380000   500000  성남
카카오     135000   600000  성남
LG화학    800000   300000  서울
현대차     200000   400000  울산
POSCO   300000   200000  포항
KB금융     45000   700000  서울
신한지주     42000   650000  서울
셀트리온    230000   550000  인천

In [114]:
# 행 열 동시 선택
# df2.loc['삼성전자', '지역'] # 인덱스 삼성전자, 지역열 
# df2.loc[['삼성전자', 'NAVER'], '지역'] # 인덱스 삼성전자, 네이버의 지역
df2.loc['삼성전자':'현대차', '현재가':'지역'] # 삼성전자~현대차까지, 현재~지역열 출력

           현재가      거래량  지역
종목명
삼성전자     70000  1000000  서울
SK하이닉스  120000   800000  서울
NAVER   380000   500000  성남
카카오     135000   600000  성남
LG화학    800000   300000  서울
현대차     200000   400000  울산