## **데이터 합치기**

#### **1. 시간 구간이 다른 데이터 합치기**
- 주식 데이터를 월별 또는 연도별로 나누어 수집한 경우, 이를 결합해 전체 데이터를 분석할 수 있도록 통합해야 함.
- 예시: 1월과 2월의 주식 거래 데이터를 각각 다른 데이터프레임으로 가지고 있을 때, 이를 합쳐서 1~2월 동안의 트렌드를 분석할 필요가 있음.

#### **2. 다른 변수(열)를 가진 데이터 합치기**
- 한 데이터프레임에는 가격 데이터(종가, 시가)가 있고, 다른 데이터프레임에는 거래량 데이터가 있는 경우, 이를 결합해 가격과 거래량의 관계를 분석할 수 있음.
- 예시: 한 데이터프레임에 '종가', '시가'만 있고, 다른 데이터프레임에 '거래량'만 있을 때, 이를 합쳐 종가와 거래량 간의 상관관계를 분석함.

#### **데이터 결합의 이유**
- **1) 전체적인 패턴 분석:**
    - 예를 들어 1월과 2월 데이터를 결합함으로써 더 긴 기간 동안의 종가 변동과 거래량 패턴을 확인할 수 있음. 이는 특정 달이나 기간에만 집중하는 것보다 더 포괄적인 인사이트를 제공함.
- **2) 종합적 상관관계 분석:**
    - 시가, 종가, 거래량 같은 여러 변수들을 결합해 상관관계를 분석할 수 있음. 이를 통해 주가 변동에 따른 거래량 변화, 특정 종목의 거래 트렌드 등을 파악할 수 있음.
- **3) 데이터의 완성도 증가:**
    - 분리된 데이터를 결합함으로써 분석에 필요한 모든 변수를 하나의 데이터프레임에 통합할 수 있음. 이를 통해 다양한 분석을 한 번에 진행할 수 있고, 시각화도 용이해짐.

### **1) concat()** : 두 개 이상의 Pandas 데이터프레임이나 시리즈를 결합하는 데 사용됨. 
- 데이터는 행(axis=0) 또는 열(axis=1)을 기준으로 결합할 수 있음
- ignore_index: True로 설정하면 기존 인덱스를 무시하고 새로운 인덱스를 부여함

In [4]:
import pandas as pd

#### **1.두개 데이터 합치기**

In [6]:
# 데이터 불러오기
df1 = pd.read_csv('07_stock_concat1.csv', index_col=0)
df1

         날짜  종목코드     종목명      종가      시가      저가       거래량  분기
0  20230101  5930    삼성전자   61000   60500   60000  15800000  Q1
1  20230102   660  SK하이닉스  105000  104500  103000  10500000  Q1
2  20230103  5930    삼성전자   61500   61000   60500  16200000  Q1
3  20230104   660  SK하이닉스  106000  105500  104000  11000000  Q1
4  20230105  5930    삼성전자   62000   61500   61000  16500000  Q1

In [7]:
# 두번째 데이터 불러오기
df2 = pd.read_csv('07_stock_concat2.csv', index_col=0)

In [10]:
#데이터 합치기
df_concat = pd.concat([df1, df2], axis=0)
df_concat

         날짜  종목코드     종목명      종가      시가      저가       거래량  분기
0  20230101  5930    삼성전자   61000   60500   60000  15800000  Q1
1  20230102   660  SK하이닉스  105000  104500  103000  10500000  Q1
2  20230103  5930    삼성전자   61500   61000   60500  16200000  Q1
3  20230104   660  SK하이닉스  106000  105500  104000  11000000  Q1
4  20230105  5930    삼성전자   62000   61500   61000  16500000  Q1
0  20230401  5930    삼성전자   63000   62500   62000  16000000  Q2
1  20230402   660  SK하이닉스  108000  107500  106500  10600000  Q2
2  20230403  5930    삼성전자   63500   63000   62500  16300000  Q2
3  20230404   660  SK하이닉스  109000  108500  107000  11100000  Q2
4  20230405  5930    삼성전자   64000   63500   63000  16600000  Q2

#### **2. 여러개 데이터 합치기(for문)**

In [32]:
# for문을 활용해서 4분기 데이터 모두 합치기

# 빈 데이터 프레임 생성
df_concat2 = pd.DataFrame()

# 1~4까지 반복
for i in range(1,5):
    # 데이터 불러오기
    dfn = pd.read_csv(f'07_stock_concat{i}.csv', index_col=0)
    
    # 기존 데이터 + 불러온 데이터 합쳐서 새로운 데이터 생성
    df_concat2 = pd.concat([df_concat2, dfn], axis=0, ignore_index=True)
    
    print(f'07_stock_concat{i} 파일 병합')

df_concat2

07_stock_concat1 파일 병합
07_stock_concat2 파일 병합
07_stock_concat3 파일 병합
07_stock_concat4 파일 병합

          날짜  종목코드     종목명      종가      시가      저가       거래량  분기
0   20230101  5930    삼성전자   61000   60500   60000  15800000  Q1
1   20230102   660  SK하이닉스  105000  104500  103000  10500000  Q1
2   20230103  5930    삼성전자   61500   61000   60500  16200000  Q1
3   20230104   660  SK하이닉스  106000  105500  104000  11000000  Q1
4   20230105  5930    삼성전자   62000   61500   61000  16500000  Q1
5   20230401  5930    삼성전자   63000   62500   62000  16000000  Q2
6   20230402   660  SK하이닉스  108000  107500  106500  10600000  Q2
7   20230403  5930    삼성전자   63500   63000   62500  16300000  Q2
8   20230404   660  SK하이닉스  109000  108500  107000  11100000  Q2
9   20230405  5930    삼성전자   64000   63500   63000  16600000  Q2
10  20230701  5930    삼성전자   64500   64000   63500  17000000  Q3
11  20230702   660  SK하이닉스  110000  109500  108500  10700000  Q3
12  20230703  5930    삼성전자   65000   64500   64000  17300000  Q3
13  20230704   660  SK하이닉스  111000  110500  109000  11200000  Q3
14  20230705  5930    삼성전자   65500   65000   64500  17600000  Q3
15  20231001  5930    삼성전자   66000   65500   65000  18000000  Q4
16  20231002   660  SK하이닉스  112000  111500  110500  10800000  Q4
17  20231003  5930    삼성전자   66500   66000   65500  18300000  Q4
18  20231004   660  SK하이닉스  113000  112500  111000  11300000  Q4
19  20231005  5930    삼성전자   67000   66500   66000  18600000  Q4

#### **3. 추가 컬럼 합치기**

In [37]:
# 데이터 불러오기
extra_df = pd.read_csv('07_stock_extra.csv', index_col=0)
extra_df

     PER   EPS
0   15.2  4000
1   14.8  3800
2   15.5  3900
3   16.0  4100
4   16.2  4200
5   13.0  3000
6   12.5  2900
7   13.2  3100
8   13.8  3200
9   14.1  3300
10  15.8  4100
11  16.5  4200
12  16.7  4300
13  17.0  4400
14  17.5  4500
15  12.2  2800
16  12.5  2700
17  13.1  3000
18  13.6  3100
19  14.2  3200

In [40]:
# 열 방향으로 합치기
# index가 같아야지 합쳐짐, reset_index(drop=True) 옵션
df_concat3 = pd.concat([df_concat2, extra_df], axis=1)
df_concat3

          날짜  종목코드     종목명      종가      시가      저가       거래량  분기   PER   EPS
0   20230101  5930    삼성전자   61000   60500   60000  15800000  Q1  15.2  4000
1   20230102   660  SK하이닉스  105000  104500  103000  10500000  Q1  14.8  3800
2   20230103  5930    삼성전자   61500   61000   60500  16200000  Q1  15.5  3900
3   20230104   660  SK하이닉스  106000  105500  104000  11000000  Q1  16.0  4100
4   20230105  5930    삼성전자   62000   61500   61000  16500000  Q1  16.2  4200
5   20230401  5930    삼성전자   63000   62500   62000  16000000  Q2  13.0  3000
6   20230402   660  SK하이닉스  108000  107500  106500  10600000  Q2  12.5  2900
7   20230403  5930    삼성전자   63500   63000   62500  16300000  Q2  13.2  3100
8   20230404   660  SK하이닉스  109000  108500  107000  11100000  Q2  13.8  3200
9   20230405  5930    삼성전자   64000   63500   63000  16600000  Q2  14.1  3300
10  20230701  5930    삼성전자   64500   64000   63500  17000000  Q3  15.8  4100
11  20230702   660  SK하이닉스  110000  109500  108500  10700000  Q3  16.5  4200
12  20230703  5930    삼성전자   65000   64500   64000  17300000  Q3  16.7  4300
13  20230704   660  SK하이닉스  111000  110500  109000  11200000  Q3  17.0  4400
14  20230705  5930    삼성전자   65500   65000   64500  17600000  Q3  17.5  4500
15  20231001  5930    삼성전자   66000   65500   65000  18000000  Q4  12.2  2800
16  20231002   660  SK하이닉스  112000  111500  110500  10800000  Q4  12.5  2700
17  20231003  5930    삼성전자   66500   66000   65500  18300000  Q4  13.1  3000
18  20231004   660  SK하이닉스  113000  112500  111000  11300000  Q4  13.6  3100
19  20231005  5930    삼성전자   67000   66500   66000  18600000  Q4  14.2  3200

#### **concat 실습**
- 2016_health_checkup_1~4번까지 데이터 합치는 코드 작성

In [41]:
df1 = pd.DataFrame()

for i in range(1, 5):
    df_n = pd.read_csv(f'2016_health_checkup_{i}.csv')
    df1 = pd.concat([df1, df_n])

df1

,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg단위),허리둘레,시력(좌),시력(우),청력(좌),...,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,구강검진 수검여부,치석,당뇨병 의사 판정,고혈압 의사 판정,간기능 이상여부,알콜성간염여부
0,604509,1,12,41,165.0,65.0,7.0,1.2,1.0,1.0,...,21.0,17.0,17.0,1.0,0,NaN,0.0,0.0,0.0,0.0
1,360197,2,17,43,130.0,25.0,50.0,0.3,0.9,1.0,...,18.0,7.0,19.0,1.0,0,NaN,0.0,0.0,0.0,1.0
2,201061,2,17,45,150.0,135.0,51.0,0.5,0.5,1.0,...,21.0,18.0,24.0,1.0,0,NaN,1.0,0.0,0.0,0.0
3,586237,2,12,41,145.0,35.0,51.0,1.5,0.7,1.0,...,15.0,14.0,18.0,3.0,0,NaN,0.0,0.0,0.0,0.0
4,922457,2,9,11,150.0,35.0,51.0,1.2,1.0,1.0,...,18.0,10.0,20.0,1.0,1,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,924026,2,7,41,NaN,NaN,999.0,0.8,1.2,1.0,...,36.0,48.0,17.0,1.0,0,NaN,0.0,0.0,0.0,0.0
249996,944802,1,7,45,NaN,NaN,77.0,0.8,0.6,1.0,...,20.0,25.0,29.0,1.0,1,0.0,0.0,0.0,0.0,0.0
249997,960034,1,12,26,NaN,NaN,84.0,0.9,1.2,2.0,...,23.0,27.0,51.0,2.0,1,1.0,0.0,0.0,0.0,0.0
249998,979986,1,6,30,NaN,NaN,76.0,1.2,1.5,1.0,...,18.0,23.0,77.0,1.0,0,NaN,0.0,0.0,0.0,0.0
249999,996778,1,6,41,NaN,NaN,76.0,1.2,1.0,1.0,...,14.0,10.0,10.0,1.0,0,NaN,0.0,0.0,0.0,0.0

### **2) merge()** : 두 개 이상의 데이터프레임을 공통 열 또는 인덱스를 기준으로 병합할 때 사용됨
- **pd.merge(left, right, how='inner', on=None, left_index=False)**
    - left, right: 병합할 두 개의 데이터프레임.
    - how: 결합 방식 지정 ('left', 'right', 'outer', 'inner').
        - 'inner' (기본값): 공통된 데이터만 결합.
        - 'left': 왼쪽 데이터프레임의 모든 데이터를 유지.
        - 'right': 오른쪽 데이터프레임의 모든 데이터를 유지.
        - 'outer': 양쪽 데이터프레임의 모든 데이터를 결합.
    - on: 병합 기준이 되는 열. 공통된 열 이름이 있을 때 사용.
    - left_index, right_index: 인덱스를 기준으로 병합할 경우 True로 설정

#### **1.inner 방식 병합 (공통된 데이터만 결합)**

In [52]:
# 데이터 불러오기
df_주가 = pd.read_csv('07_stock_merge_주가.csv', index_col=0)
df_재무정보 = pd.read_csv('07_stock_merge_재무정보.csv', index_col=0)
print(df_주가.shape, df_재무정보.shape)

(10, 6) (10, 4)

In [53]:
# '종목코드'를 기준으로 병합 (inner)
df_merged_inner = pd.merge(df_주가, df_재무정보, on='종목코드', how='inner')
df_merged_inner

    종목코드      종목명      종가      시가      저가       거래량  부채비율   PER   EPS
0   5930     삼성전자   61000   60000   59500  15800000  40.5  15.2  4000
1    660   SK하이닉스  105000  104500  103500  10500000  35.0  14.5  3500
2  35420      네이버  260000  255000  250000   5000000  20.0  30.0  5000
3  68270     셀트리온  175000  173000  171000   3500000  45.0  25.2  8000
4   5380      현대차  220000  215000  210000   2500000  38.0  13.5  4500
5  96770  SK이노베이션  150000  147000  145000   1800000  42.5  12.8  4000
6  66570     LG전자  120000  118000  115000   2100000   NaN  10.9  3000
7  17670    SK텔레콤  300000  290000  285000   1000000  29.0  18.2  5500
8  34730       두산   50000   48000   47000    500000  55.0   8.5  1500

#### **2. outer 방식 병합 (모든 데이터 결합)**
- 두 데이터프레임의 모든 행을 결합하며, 공통되지 않는 부분은 NaN으로 표시됨.

In [54]:
# '종목코드'를 기준으로 병합 (inner)
df_merged_outer = pd.merge(df_주가, df_재무정보, on='종목코드', how='outer')
df_merged_outer

,종목코드,종목명,종가,시가,저가,거래량,부채비율,PER,EPS
0,5930.0,삼성전자,61000.0,60000.0,59500.0,15800000.0,40.5,15.2,4000.0
1,660.0,SK하이닉스,105000.0,104500.0,103500.0,10500000.0,35.0,14.5,3500.0
2,35420.0,네이버,260000.0,255000.0,250000.0,5000000.0,20.0,30.0,5000.0
3,51910.0,LG화학,780000.0,770000.0,760000.0,3000000.0,NaN,NaN,NaN
4,68270.0,셀트리온,175000.0,173000.0,171000.0,3500000.0,45.0,25.2,8000.0
5,5380.0,현대차,220000.0,215000.0,210000.0,2500000.0,38.0,13.5,4500.0
6,96770.0,SK이노베이션,150000.0,147000.0,145000.0,1800000.0,42.5,12.8,4000.0
7,66570.0,LG전자,120000.0,118000.0,115000.0,2100000.0,NaN,10.9,3000.0
8,17670.0,SK텔레콤,300000.0,290000.0,285000.0,1000000.0,29.0,18.2,5500.0
9,34730.0,두산,50000.0,48000.0,47000.0,500000.0,55.0,8.5,1500.0
10,NaN,NaN,NaN,NaN,NaN,NaN,50.0,20.5,9000.0

#### **merge 실습**
**1) 고객 데이터와 구매 데이터를 결합하여 고객별 총 구매금액 및 구매수량 데이터 만들기**</br>
**2) 연령열 추가하기**</br>
**3) 성별별 총 매출, 총 구매 수량 구하기**</br>
- 데이터 불러오기
    - 04_store_member.csv : 회원 정보
    - 04_store_product_1.csv : 회원들의 구매 정보
- 04_store_product_1.csv, 고객별 구매 금액, 구매 수량 합계 테이블 만들기
- 연령열 만들기
- 성별별 총 구매 금액, 구매 수량 통계 도출하기

In [61]:
# 데이터 불러오기
df_member = pd.read_csv('./04_store_member.csv')
print(df_member.shape)
df_member.head(3)

(4396, 6)

   회원번호  회원상태 성별 결혼유무               주소      생년
0  2101  정상회원  여   기혼  서울 강북구 미아동 134-  1967.0
1  2102  정상회원  여  NaN   경기 용인시 수지구 동천동  1947.0
2  2103  정상회원  여   기혼   경기 용인시 수지구 동천동  1972.0

In [62]:
# 데이터 불러오기
df_product = pd.read_csv('./04_store_product_1.csv')
print(df_product.shape)
df_product.head(3)

(130893, 11)

,공급일자,물품코드,물품대분류,물품중분류,물품소분류,물품명,구매수량,구매금액,구매매장,반품_원거래일자,회원번호
0,20170201,50301001,채소,과일채소,딸기,딸기(1kg),1.0,13600,매장1,NaN,2102
1,20170201,80201053,간식,떡,가래떡,현미가래떡(400g),1.0,99999999,매장1,NaN,2102
2,20170201,110104033,음료,음료,음료기타,개복숭아감식초(700ml),1.0,13000,매장1,NaN,2103

#### **회원 번호를 기준으로 구매 금액, 수량 합계 테이블 만들기**

In [68]:
# 회원 번호를 기준으로 구매 금액, 수량 합계 구하기
df_product2 = df_product.groupby('회원번호')[['구매금액', '구매수량']].sum()
df_product2

           구매금액    구매수량
회원번호
2102  102093159   472.5
2103    7904400  1586.4
2104     389040   112.0
2105    3067930   602.0
2106      54550    25.0
...         ...     ...
6471       1600     1.0
6474     709400   175.0
6478       2600     1.0
6489      22100    14.0
6490      13400     2.0

[1383 rows x 2 columns]

#### **inner join**

In [73]:
# 첫 번째 데이터의 회원 번호를 기준으로, 첫번째 데이터에 있는 데이터만 병합
df_inner = pd.merge(df_product2, df_member, on='회원번호', how='inner')

#### **right join**

In [74]:
# 두 번째 데이터의 회원 번호를 기준으로 병합, 결측행이 많음
df_right = pd.merge(df_product2, df_member, on='회원번호', how='right')

#### **outer join**

In [75]:
df_outer = pd.merge(df_product2, df_member, on='회원번호', how='outer')

In [76]:
# 연령열 만들기
df_inner['연령'] = 2024 - df_inner['생년']
df_inner.head()

   회원번호       구매금액    구매수량  회원상태 성별 결혼유무              주소      생년    연령
0  2102  102093159   472.5  정상회원  여  NaN  경기 용인시 수지구 동천동  1947.0  77.0
1  2103    7904400  1586.4  정상회원  여   기혼  경기 용인시 수지구 동천동  1972.0  52.0
2  2104     389040   112.0  정상회원  여  NaN  경기 용인시 수지구 성복동  1969.0  55.0
3  2105    3067930   602.0  정상회원  여   기혼  경기 용인시 수지구 동천동  1948.0  76.0
4  2106      54550    25.0  정상회원  여  NaN  경기 용인시 수지구 상현동  1953.0  71.0

In [1]:
# 성별에 따른 구매 금액 및 구매 수량
df_inner[['구매금액', '구매수량', '성별', '연령']].groupby('성별').sum()

NameError: name 'df_inner' is not defined