## **Pandas 데이터 요약하기**
- 데이터 요약은 데이터를 이해하고 분석하는 첫 번째 단계로 매우 중요함.
- 데이터셋이 커질수록 개별 데이터를 일일이 확인하기 어렵기 때문에, 요약을 통해 주요 패턴과 특성을 빠르게 파악할 수 있음.
- 이를 통해 데이터의 분포, 통계적 경향 등을 파악하고, 추가 분석 방향을 설정할 수 있음.

### **왜 데이터 요약**
- **1. 데이터의 전반적인 분포 파악:** 수백, 수천 개의 행이 있는 데이터셋에서 중요한 패턴을 빠르게 찾아내기 위해 요약이 필요함.
- **2. 특정 그룹별 통계 분석:** 데이터의 그룹별로 중요한 통계를 계산할 수 있음.
- **3. 데이터 이상치 및 누락 데이터 확인:** 요약을 통해 데이터의 결측값이나 이상치 여부를 빠르게 확인할 수 있음.
- **4. 데이터의 주요 지표 추출:** 평균, 중간값, 최소값, 최대값 등의 주요 지표를 통해 데이터의 핵심 정보를 파악할 수 있음.

### **1) pivot_table() :** 특정 열을 기준으로 데이터를 요약하고 집계할 때 사용됨. 
- index와 values를 지정하여 데이터를 그룹화하고, 각 그룹의 값을 요약
- 피벗 테이블은 엑셀에서 많이 사용되는 개념으로, 판다스에서도 데이터 요약에 매우 유용함.

**주요 인수**
- data: 피벗 테이블을 만들 데이터프레임.
- values: 집계하려는 열. (예: 매출액, 거래량)
- index: 그룹화할 행 기준 열. (예: 제품명, 날짜)
- columns: 그룹화할 열 기준. (예: 분기, 카테고리)
- aggfunc: 적용할 집계 함수. 기본값은 'mean'이며, 'sum', 'count', 'max', 'min' 등의 함수 사용 가능.
- margins: 행과 열의 총계를 포함할지 여부. 기본값은 False.
- margins_name: 총계에 붙일 이름. 기본값은 'All'.

In [2]:
import pandas as pd

In [29]:
df = pd.read_csv('./08_pivot_제품.csv', index_col=0)
df

    지역          제품  분기  판매량      매출액  할인율
0   서울  삼성 갤럭시 S21  Q1  100  1000000    5
1   부산  삼성 갤럭시 S21  Q1  150  1500000   10
2   서울  LG OLED TV  Q1  200  2000000    0
3   부산  LG OLED TV  Q1  250  2500000    5
4   서울   애플 아이폰 12  Q1  300  3000000   10
5   부산   애플 아이폰 12  Q1  350  3500000   15
6   서울  삼성 갤럭시 S21  Q2  110  1100000    5
7   부산  LG OLED TV  Q2  160  1600000    0
8   서울   애플 아이폰 12  Q2  210  2100000   10
9   부산  삼성 갤럭시 S21  Q2  120  1200000    5
10  서울  LG OLED TV  Q2  170  1700000    0
11  부산   애플 아이폰 12  Q2  220  2200000   15
0   서울  삼성 갤럭시 S21  Q3  130  1300000    5
1   부산  LG OLED TV  Q3  180  1800000    0
2   서울   애플 아이폰 12  Q3  230  2300000   10
3   부산  삼성 갤럭시 S21  Q3  140  1400000    5
4   서울  LG OLED TV  Q3  190  1900000    0
5   부산   애플 아이폰 12  Q3  240  2400000   15
0   서울  삼성 갤럭시 S21  Q4  150  1500000    5
1   부산  LG OLED TV  Q4  200  2000000    0
2   서울   애플 아이폰 12  Q4  250  2500000   10
3   부산  삼성 갤럭시 S21  Q4  160  1600000    5
4   서울  LG OLED TV  Q4  210  2100000    0
5   부산   애플 아이폰 12  Q4  260  2600000   15

**데이터 설명**
- 지역: 제품이 판매된 지역 (서울, 부산).
- 제품: 판매된 제품 이름 (삼성 갤럭시 S21, LG OLED TV, 애플 아이폰 12).
- 분기: 제품이 판매된 분기 (Q1, Q2).
- 판매량: 각 제품의 판매 수량.
- 매출액: 각 제품의 매출 금액 (원).
- 할인율: 판매 시 적용된 할인율 (%).

#### **1. 기본 구조: index와 values 사용**
- pivot_table은 평균을 계산

In [23]:
# 제품별 매출액 평균, 기본 피벗테이블 집계는 평균
pd.pivot_table(data=df, index='제품', values='판매량')

              판매량
제품
LG OLED TV  195.0
삼성 갤럭시 S21  132.5
애플 아이폰 12   257.5

#### **Step 2: 집계 방식 변경 (aggfunc)**
- aggfunc 인수를 사용하면 다양한 방식으로 집계

#### **aggfunc 파라미터**

- mean: 평균
- sum: 합계
- min: 최소값
- max: 최대값
- count: 값의 개수
- std: 표준편차
- var: 분산
- median: 중앙값
- first: 첫 번째 값
- last: 마지막 값
- prod: 곱셈
- nunique: 고유값의 개수

**판매량의 합계 계산**

In [22]:
# aggfunc 파라미터를 활용해서 합계로 집계하기
pd.pivot_table(data=df, index='제품', values='판매량', aggfunc='sum')

             판매량
제품
LG OLED TV  1560
삼성 갤럭시 S21  1060
애플 아이폰 12   2060

#### **Step 3: 다중 집계 (여러 값과 집계 방식 사용)**
- 여러 개의 values와 집계 함수를 동시에 사용

**판매량과 매출액의 합계 및 평균 계산**

In [26]:
# 제품별 지역별 매출액, 판매량 합계
pd.pivot_table(data=df, index='제품', values=['판매량', '매출액'], aggfunc={'판매량': 'sum', '매출액': 'mean'})

                매출액   판매량
제품
LG OLED TV  1950000  1560
삼성 갤럭시 S21  1325000  1060
애플 아이폰 12   2575000  2060

#### **Step 4: 다중 인덱스 사용 (index에 여러 열 지정)**
-  index에 여러 열을 지정하면, 데이터를 더 세분화하여 분석

**제품과 지역을 기준으로 판매량과 매출액 분석**

In [35]:
# 데이터 프레임 메소드로 생성하기
pd.pivot_table(data=df, index=['제품', '지역'], values=['판매량', '매출액'], aggfunc='sum')

                    매출액   판매량
제품         지역
LG OLED TV 부산   7900000   790
           서울   7700000   770
삼성 갤럭시 S21 부산   5700000   570
           서울   4900000   490
애플 아이폰 12  부산  10700000  1070
           서울   9900000   990

#### **Step 5: 열을 기준으로 데이터 정리 (columns 사용)**
- columns 파라미터를 사용하면 데이터의 특정 열을 **컬럼(열)**으로 변환

**분기를 기준으로 제품 판매량 분석**

In [36]:
pd.pivot_table(data=df, index='제품', values='판매량', columns='분기', aggfunc='sum')

분기           Q1   Q2   Q3   Q4
제품
LG OLED TV  450  330  370  410
삼성 갤럭시 S21  250  230  270  310
애플 아이폰 12   650  430  470  510

#### **Step 6: 총합 추가 (margins 사용)**
- 총합을 계산하여 피벗 테이블에 포함

In [39]:
# margin=True : 총합 , margin_name='총합' 총합 이름 설정
pd.pivot_table(data=df, index='제품', values='판매량', columns='분기', aggfunc='sum', margins=True, margins_name='총합' )

분기            Q1   Q2    Q3    Q4    총합
제품
LG OLED TV   450  330   370   410  1560
삼성 갤럭시 S21   250  230   270   310  1060
애플 아이폰 12    650  430   470   510  2060
총합          1350  990  1110  1230  4680

In [40]:
# 총합 행 총합 삭제
pivot = pd.pivot_table(data=df, index='제품', values='판매량', columns='분기', aggfunc='sum', margins=True, margins_name='총합' ).drop('총합', axis=0)
pivot

분기           Q1   Q2   Q3   Q4    총합
제품
LG OLED TV  450  330  370  410  1560
삼성 갤럭시 S21  250  230  270  310  1060
애플 아이폰 12   650  430  470  510  2060

## **Pivot_table 실습**

In [41]:
df1 = pd.read_csv('./01_Contract_Data.csv')

In [42]:
df1.head()

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,5.0,농협회원조합
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합

#### **데이터 설명**

**렌탈 고객 데이터 정보**
- Index: 각 행의 고유 식별자 (인덱스).
- Member_ID: 고객의 고유 식별자 (회원 번호).
- Sales_Type: 판매 유형. 예: 렌탈, 멤버십 등.
- Contract_Type: 계약 유형. 예: 일반계약, 교체계약, 재계약 등.
- Channel: 판매 채널. 예: 영업방판, 홈쇼핑/방송 등.
- Datetime: 계약 날짜. 계약이 체결된 날짜를 나타냄.
- Term: 계약 기간 (개월 단위). 예: 60개월, 12개월 등.
- Payment_Type: 결제 방식. 예: CMS(자동이체), 카드이체 등.
- Product_Type: 제품 유형. 예: DES-1 (제품 코드).
- Amount_Month: 월별 결제 금액.
- Customer_Type: 고객 유형. 예: 개인.
- Age: 고객 나이.
- Address1: 고객의 주소 (1차 주소).
- Address2: 고객의 주소 (2차 주소).
- State: 계약 상태. 예: 계약확정, 기간만료 등.
- Overdue_count: 연체 횟수.
- Overdue_Type: 연체 유형. 예: 있음, 없음.
- Gender: 고객 성별. 예: 남자, 여자.
- Credit_Rank: 신용 등급.
- Bank: 결제 은행 또는 카드사. 예: 새마을금고, 현대카드 등.

#### **1. 고객들의 유입 채널 별 월랜탈 매출(평균, 합계)**

In [46]:
# 평균
df1.pivot_table(index='Channel', values='Amount_Month')

          Amount_Month
Channel
대형마트A     97016.330159
대형마트C     95276.974790
대형마트E    100423.647295
대형마트H    100025.333333
대형마트N     76514.457831
영업방판     100322.794631
자체홈페이지    98402.500000
재계약       67176.744186
전단홍보     104048.571429
전문매장H     72514.008677
전문매장Z     98127.363184
직영계열사A   104970.000000
직영계열사B   111300.000000
직영유통사    119011.117021
홈쇼핑/방송    89092.232411
홈쇼핑/인터넷   96685.600000

In [47]:
# 합계
df1.pivot_table(index='Channel', values='Amount_Month', aggfunc='sum')

         Amount_Month
Channel
대형마트A       458402160
대형마트C        11337960
대형마트E       150334200
대형마트H        22505700
대형마트N         6350700
영업방판       2384371860
자체홈페이지       11808300
재계약         147318600
전단홍보         58267200
전문매장H       234002706
전문매장Z       118341600
직영계열사A        2099400
직영계열사B        2114700
직영유통사        22374090
홈쇼핑/방송     1156149900
홈쇼핑/인터넷      36257100

#### **2. 고객들의 성별 및 유입 채널 별 월랜탈 매출 및 연체건 수(합계)**

In [48]:
df1.pivot_table(index=['Gender', 'Channel'], values=['Amount_Month', 'Overdue_count'], aggfunc='sum')

                Amount_Month  Overdue_count
Gender Channel
남자     대형마트A       135033600            351
       대형마트E        51570900             89
       대형마트H         8149500             21
       대형마트N         3120900              0
       영업방판        761853300           2083
       자체홈페이지        4813500              1
       재계약          51653700            167
       전단홍보         17594700             21
       전문매장H        49461600            128
       전문매장Z        47891700             43
       홈쇼핑/방송      352808400            476
       홈쇼핑/인터넷       9774900             20
여자     대형마트A       323368560            553
       대형마트C        11337960              0
       대형마트E        98763300            103
       대형마트H        14356200             22
       대형마트N         3229800              0
       영업방판       1622518560           2804
       자체홈페이지        6994800              3
       재계약          95664900            148
       전단홍보         40672500             80
       전문매장H       184541106             64
       전문매장Z        70449900             88
       직영계열사A        2099400              0
       직영계열사B        2114700              0
       직영유통사        22374090            172
       홈쇼핑/방송      803341500            795
       홈쇼핑/인터넷      26482200             47

#### **3. 판매유형별 연간/월별 월랜탈 매출 합계, 엑셀파일로 저장하기**

In [50]:
# 날짜 타입으로 데이터 변환
df1['Datetime(변환)'] = pd.to_datetime(df1['Datetime'])
df1

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,...,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank,Datetime(변환)
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,...,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고,2019-05-06
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,...,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드,2020-02-20
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,...,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행,2019-02-28
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,...,39.0,경기도,경기도,계약확정,0,없음,남자,5.0,농협회원조합,2019-05-13
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,...,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합,2019-05-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,...,47.0,경기도,경기도,계약확정,0,없음,남자,NaN,기업은행,2019-03-01
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,...,42.0,경기도,경기도,계약확정,0,없음,여자,8.0,새마을금고,2019-04-01
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,...,65.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드,2019-04-01
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,...,54.0,서울특별시,서울특별시,계약확정,0,없음,여자,2.0,롯데카드,2020-02-06
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,...,53.0,서울특별시,서울특별시,계약확정,0,없음,여자,8.0,신한은행,2019-04-24

In [53]:
# 연도 및 월 열 추가
df1['연도'] = df1['Datetime(변환)'].dt.year
df1['월'] = df1['Datetime(변환)'].dt.month
df1

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,...,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank,Datetime(변환),연도,월
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,...,경기도,계약확정,0,없음,여자,9.0,새마을금고,2019-05-06,2019,5
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,...,경기도,계약확정,0,없음,남자,2.0,현대카드,2020-02-20,2020,2
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,...,경기도,계약확정,0,없음,여자,8.0,우리은행,2019-02-28,2019,2
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,...,경기도,계약확정,0,없음,남자,5.0,농협회원조합,2019-05-13,2019,5
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,...,경기도,기간만료,12,있음,남자,8.0,농협회원조합,2019-05-10,2019,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,...,경기도,계약확정,0,없음,남자,NaN,기업은행,2019-03-01,2019,3
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,...,경기도,계약확정,0,없음,여자,8.0,새마을금고,2019-04-01,2019,4
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,...,서울특별시,계약확정,0,없음,여자,1.0,롯데카드,2019-04-01,2019,4
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,...,서울특별시,계약확정,0,없음,여자,2.0,롯데카드,2020-02-06,2020,2
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,...,서울특별시,계약확정,0,없음,여자,8.0,신한은행,2019-04-24,2019,4

In [56]:
df1.pivot_table(index='Sales_Type', columns=['연도', '월'],\
                values='Amount_Month', aggfunc='sum').to_excel('연도별월별_월별렌탈비용.xlsx')

In [57]:
pd.read_excel('연도별월별_월별렌탈비용.xlsx')

,연도,2019,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,2020,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,월,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,11.0,12.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0
1,Sales_Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,렌탈,394690080.0,581147940.0,423192960.0,318915930.0,263786940.0,236969310.0,313217310.0,209958420.0,206670360.0,...,133427430.0,243143700.0,169887480.0,172963560.0,146727300.0,119676630.0,84609240.0,76746600.0,119785560.0,22321260.0
3,멤버십,17205900.0,44238291.0,27736254.0,20259312.0,19053555.0,17510016.0,24422919.0,14708643.0,15138687.0,...,8778570.0,17624838.0,10732548.0,10211535.0,10317633.0,8243748.0,5075889.0,5541123.0,7771983.0,1729047.0

#### **4. 총합, 새로운 열 추가**
- a. 결재 은행별, 월 렌탈 비용 합계, 총합 테이블
- b. 렌탈 상품 유형별, 월 렌탈 매출 합계, 총합, 연간으로 나누어서 보기
- b-1. 2019년대비 20년 증감액과 증감율 열 추가

**a. 결재 은행별, 월 렌탈 비용 합계, 총합 테이블**

In [58]:
df1.pivot_table(index='Bank', values='Amount_Month', aggfunc='sum', margins=True)

           Amount_Month
Bank
BC카드          120408150
NH농협카드           545400
SC제일은행         42455400
SK증권              90900
경남은행           42701700
광주은행           32907000
국민은행          572284179
국민카드          125086200
기업은행          190178979
농협중앙회         371847000
농협회원조합        601133079
대구은행           71830800
대신증권             105900
대우증권             163800
롯데카드          896422200
메리츠종합금융증권         87900
미래에셋증권           499500
부산은행           84919500
산림조합중앙회           96900
산업은행            2388900
삼성증권             603300
삼성카드           83970000
상호저축은행            96900
새마을금고          92481900
수협중앙회          15868800
수협카드             105900
신한금융투자           375600
신한은행          337695600
신한카드          146170500
신협중앙회          32284500
씨티은행           15556500
씨티카드             124200
외환은행           56088900
외환카드           50771400
우리은행          324049500
우리카드             272700
우체국            68319300
유안타증권           2481300
전북은행           18551100
제주은행            3738300
하나SK             572400
하나대투증권            66900
하나은행          139140300
하이투자증권            87900
한국투자증권           390600
현대증권            1077900
현대카드           83619000
All          4630714587

**b. 렌탈 상품 유형별, 월 렌탈 매출 합계, 총합, 연간으로 나누어서 보기**

In [62]:
df2 = df1.pivot_table(index='Product_Type', values='Amount_Month', columns='연도',aggfunc='sum')
df2

연도                  2019       2020
Product_Type
DES-1         2946278610  748837116
DES-2          631877970  155779320
DES-3A         157162560   39922500
DES-R4          33891300    8437200
ERA             62944500   14171100
MMC             17540100    5193900

**b-1. 2019년대비 20년 증감액과 증감율 열 추가**

In [68]:
df2['증감액'] = df2[2020] - df2[2019]
df2['증감율'] = (df2['증감액'] / df2[2019])*100
df2

연도                  2019       2020         증감액        증감율
Product_Type
DES-1         2946278610  748837116 -2197441494 -74.583629
DES-2          631877970  155779320  -476098650 -75.346613
DES-3A         157162560   39922500  -117240060 -74.597958
DES-R4          33891300    8437200   -25454100 -75.105115
ERA             62944500   14171100   -48773400 -77.486357
MMC             17540100    5193900   -12346200 -70.388424